### ISSUE TITLE
bug: JavaScript heap out of memory during the replicator sync

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1015]
**What is the bug?**

Ran into the following error while running the replicate-data-postgres example

- Node v18.12.1 & v18.16.0
- Running without the docker image
- t2.micro - 1vCPU, 1 GB memory, 8GB disk

```
<--- Last few GCs --->

[276753:0x5580a4583c70]    25630 ms: Mark-sweep (reduce) 473.6 (483.8) -> 472.3 (483.6) MB, 1739.8 / 0.0 ms  (average mu = 0.120, current mu = 0.024) allocation failure; scavenge might not succeed
[276753:0x5580a4583c70]    26808 ms: Mark-sweep (reduce) 473.7 (483.8) -> 472.9 (484.1) MB, 1166.6 / 0.0 ms  (average mu = 0.074, current mu = 0.009) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fd1fce00b5c node::Abort() [/lib64/libnode.so.108]
 2: 0x7fd1fccee8ab  [/lib64/libnode.so.108]
 3: 0x7fd1fe0e66b4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib64/libnode.so.108]
 4: 0x7fd1fe0e6a9c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib64/libnode.so.108]
 5: 0x7fd1fe2c1d89  [/lib64/libnode.so.108]
 6: 0x7fd1fe2da9f3 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib64/libnode.so.108]
 7: 0x7fd1fe2b4af6 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib64/libnode.so.108]
 8: 0x7fd1fe2b5ea7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib64/libnode.so.108]
 9: 0x7fd1fe298862 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType, v8::internal::Handle<v8::internal::AllocationSite>) [/lib64/libnode.so.108]
10: 0x7fd1fe2a265c v8::internal::Factory::NewJSObjectFromMap(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType, v8::internal::Handle<v8::internal::AllocationSite>) [/lib64/libnode.so.108]
11: 0x7fd1fe2a3029 v8::internal::Factory::NewJSArrayWithUnverifiedElements(v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, int, v8::internal::AllocationType) [/lib64/libnode.so.108]
12: 0x7fd1fe2a3136 v8::internal::Factory::NewJSArrayWithElements(v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, int, v8::internal::AllocationType) [/lib64/libnode.so.108]
13: 0x7fd1fe6809e6 v8::internal::Runtime_StringSplit(int, unsigned long*, v8::internal::Isolate*) [/lib64/libnode.so.108]
14: 0x7fd1fdfd5af9  [/lib64/libnode.so.108]
```

**How can it be reproduced? (optional)**
Replicator had terminated on June 7. Restarted it after several days on June 11 & it was syncing with the hub for a minute or 2 before it ran into the oom fatal error.

**Additional context (optional)**

**Comment by manan19** [comment]
cc @sds

**Comment by manan19** [comment]
Tried running it locally and it's definitely using a leaking. Used up 20+ GB of memory in less than 5 minutes

![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/bf57a9f5-a865-42ee-90e5-84a84a089a90)

**Comment by sds** [comment]
@manan19 just want to confirm: which commit are you running the example from? If the example code was copied from a while back, there was a memory issue in the early implementation, but my recollection is we got it down to consuming well under 0.5 GB of RAM last I checked.

**Comment by sds** [comment]
Also: which version of Node are you using?

**Comment by manan19** [comment]
@sds Running top of main. Updated again today and tried it, but still seeing the same issue.

Node version is v18.12.1

**Comment by manan19** [comment]
// If you're hitting out-of-memory errors, try decreasing this to reduce overall
// memory usage.
const MAX_PAGE_SIZE = 3_000;

Reducing the page size to 30 didn't help either.

**Comment by manan19** [comment]
Updating to the tip of the main with the update for indexing links seems to have fixed the issue.

**Comment by sds** [comment]
Was literally about to post saying I was unable to reproduce this on either Node 18 or 20, on macOS natively or within a Docker container (took a while to run all of these configurations).

I'm not sure what issue you were hitting, but if you're seeing this again let us know!

**Comment by Caruso33** [comment]
@manan19 seems like modifying the `docker-compose.yaml` and setting the `--max-old-space-size` with the ram size of the system fixed it for me (8GB system).

`command: ['node', '--max-old-space-size=8192', 'build/app.js', 'start']`

before `command: ['node', 'build/app.js', 'start']`

https://github.com/farcasterxyz/hub-monorepo/blob/a6367658e5c518956a612f793bec06eef5eb1a35/apps/replicator/docker-compose.yml#L11
