### ISSUE TITLE
feat(replicator): backfill fnames in postgres indexer

### ISSUE THREAD

**Issue by zachterrell57** [farcasterxyz/hub-monorepo#1040]
**What is the feature you would like to implement?**
It would be useful if the postgres replicator example included the ability to backfill all existing fnames instead of just ingesting new fnames

**Why is this feature important?**
As it's currently implemented, it is impossible (without extra work) to backfill the `fname` table with all existing fnames currently in the contract. Having partial fname data makes it impossible to guarantee certain queries will work, such as looking up a user by fname 

**Will the protocol spec need to be updated??**
No

**Comment by sds** [comment]
Implemented in the new replicator app in #1462.
