### ISSUE TITLE
bug (hubble): reduce log spam

### ISSUE THREAD

**Issue by TheLDB** [farcasterxyz/hub-monorepo#1090]
**What is the bug?**
When running a hub (on the latest version, 1.3.3), there is a ton of log spam, specifically repeated messages around the following error:
- `bad_request.prunable`

**How can it be reproduced? (optional)**
Just spin up a Hub using Docker, specifically I am on an m5.large, in us-west-2

<img width="1512" alt="Screenshot 2023-07-07 at 14 00 56" src="https://github.com/farcasterxyz/hub-monorepo/assets/29960599/1115e05e-a746-4041-bcf0-7e4b91bb5a1a">

**Comment by varunsrin** [comment]
The issue above is due to a bug that causes sync thrash. But in general, we emit far too many logs to be useful by default. 

We should move most of these noisy logs to debug, and ensure that we only log info and above for most of our logs.

**Comment by adityapk00** [comment]
Reduced the number of log entries by:
- Merging "success" log events during sync (Individual rpc/gossip success are still emitted)
- Removing duplicate log entries during gossip peer discovery
- Consolidate multiple log lines into one with more data. 

All original logs are still logged as "debug", so you can get back all the logs by changing the log level to "debug"

Overall, for a fresh node starting from scratch, the log size reduces from 835 MB -> 56 MB (-90%)
