### ISSUE TITLE
bug (hub-web/examples/chron-feed): Example doesn't run out of box

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1104]
**What is the bug?**
The example doesn't run out of the box. Gives the following error

```
HubError: Connection failed: please check that the hub’s address, ports and authentication config are correct. Response closed without headers
```

**How can it be reproduced? (optional)**
yarn install 
yarn start

**Comment by xinyahao** [comment]
How did you solve it? @manan19

**Comment by manan19** [comment]
@xinyahao Sadly, I haven't solved it

**Comment by fffilimonov** [comment]
It works now.
Looks like it was an issue with this server:
const HUB_URL = "nemes.farcaster.xyz:2283"; // URL of the Hub

**Comment by xinyahao** [comment]
My device has a proxy enabled. Just turning off the proxy should suffice.
