### ISSUE TITLE
bug: hubs running out of space

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1106]
**What is the bug?**

Users are reporting that Hubs are running out of space even on v1.3.3 

**How can it be reproduced? (optional)**

Users deodad and cameron on Farcaster have reported issues. deodad also reported seeing a lot of iterator logs, which might indicate that the previous issue isn't fully fixed.

**Comment by adityapk00** [comment]
Increased the logging in this PR: https://github.com/farcasterxyz/hub-monorepo/pull/1107

**Comment by adityapk00** [comment]
Switch to managed iterators: https://github.com/farcasterxyz/hub-monorepo/pull/1134

**Comment by varunsrin** [comment]
fix released with v1.4.1

**Comment by varunsrin** [comment]
this issue isn't fully resolved yet, but is dependent on #1122 which is the active tracking ticket

**Comment by adityapk00** [comment]
This PR should resolve it:
https://github.com/farcasterxyz/hub-monorepo/pull/1156
