### ISSUE TITLE
feat: permissionless hub peering

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1124]
**What is the feature you would like to implement?**

Allow mainnet hubs to peer without having to join a special allowlist.

**Comment by varunsrin** [comment]
@adityapk00 working on a spec

**Comment by adityapk00** [comment]
- Score FIDs, and then merge/rate limit based on the FID score
- make allowedPeers optional, prioritized
- Potentially score peers
