### ISSUE TITLE
bug(examples/postgres-replicator): Casts table is missing image url embeds

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1166]
**What is the bug?**
The casts table is missing the image URL. Assuming the URL is supposed to be part of the embeds because it was a screenshot pasted into the desktop Merkle client.

Ran the following query. Attaching screenshot results.
`select * from casts where fid = 191 order by timestamp desc limit 5`
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/2708cbca-b7ce-4da6-9dca-4fe70b0c38b8)

vs. relevant casts with screenshots - https://warpcast.com/manan/0xe9ae9d, https://warpcast.com/manan/0xc06f71

**How can it be reproduced? (optional)**
Don't know yet. Maybe other Postgres replicator users can try to confirm if they're seeing the same issue.

**Comment by davidfurlong** [comment]
The example uses the `embedsDeprecated` property; it should be updated to use the new `embedCastIds` and `embedCastUrls`, with `embedsDeprecated` being a fallback for `embedCastUrls`

**Comment by manan19** [comment]
This was fixed in #1174
