### ISSUE TITLE
feat: application attribution for messages

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#118]
**What is the feature you would like to implement?**
Allow messages to carry data that shows which client / application generated it

**Why is this feature important?**
Allowing attribution is useful for proving which applications are driving usage on the network, and also for moderation if certain applications are known to generate low quality or spammy content.

**Will the protocol spec need to be updated??**
Yes, section 2.2 will need to be updated 

**How should this feature be built? (optional)**
This could be done in a "no trust" way similar to HTTP headers or in a trusted way requiring a signature from each application, which have different implementation complexity vs. trustability tradeoffs.

**Comment by sds** [comment]
This is now implemented by virtue of on-chain signers including the requester FID, which is the application that is signing on behalf of the user.
