### ISSUE TITLE
hub-web/HubError: This environment's XHR implementation cannot support binary transfer.

### ISSUE THREAD

**Issue by xinyahao** [farcasterxyz/hub-monorepo#1183]
Building a client in the React Native environment. When calling any API, an error prompt occurs.

Is it an issue with my build, or do I need to handle grpc-web differently in the React Native environment?

Code：
const client = getHubRpcClient(HUB_URL, {});
const castsResult = await client.getCastsByFid({fid: FID});

react native version --- 0.72.3

**Comment by deodad** [comment]
We don't have official support for RN at the moment but are working towards it, see #1009.

Could you post the specifics error you're seeing? Are you using [@improbable-eng/grpc-web-react-native-transport](https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web-react-native-transport)?

**Comment by xinyahao** [comment]
Problem solved
close
