### ISSUE TITLE
bug (hubble): At least 1 preferred name message is missing

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1190]
**What is the bug?**
Replicator index does not return Varun's preferred name switch to varunsrin.eth

![telegram-cloud-photo-size-1-5046554172022959045-y](https://github.com/farcasterxyz/hub-monorepo/assets/377624/5cce23f7-5239-40f4-8450-3014f7a7bfc6)

**How can it be reproduced? (optional)**
Fetch data from the user_data table in the replicator

**Additional context (optional)**
- Replicator is pointed at names

**Comment by varunsrin** [comment]
Warpcast did not correctly collect proofs for some users who verified their address a long time ago. @cmlad recently made a change to revert all those proofs from Warpcast, which should eliminate this issue. 

Can you verify that this works on your end?

**Comment by manan19** [comment]
Confirming that it works.
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/f1b076f0-9452-4e87-83a3-62e92a8fe806)
