### ISSUE TITLE
bug(examples/replicate-data-postgres): Duplicate Key Violation in onLinkAdd function

### ISSUE THREAD

**Issue by christopherwxyz** [farcasterxyz/hub-monorepo#1221]
https://github.com/farcasterxyz/hub-monorepo/blob/65a4faff6656dba276468f92bd9efde49e2dbcca/packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts#L639

### Description:
I encountered an error in the onLinkAdd function. The error message suggests that there is a violation of a unique constraint, specifically "links_fid_target_fid_type_unique," when inserting new records into the "links" table.

Postgres will fail, breaking the Promise. This will cause the application to fail and exit with status code 1. 

### Error Message:

```console
db-postgres-1  | 2023-08-05 12:51:33.130 UTC [36] ERROR:  duplicate key value violates unique constraint "links_fid_target_fid_type_unique"
db-postgres-1  | 2023-08-05 12:51:33.130 UTC [36] DETAIL:  Key (fid, target_fid, type)=(976, 251, follow) already exists.
db-postgres-1  | 2023-08-05 12:51:33.130 UTC [36] STATEMENT:  insert into "links" ("hash", "timestamp", "target_fid", "type", "fid") values ($1, $2, $3, $4, $5) on conflict ("hash") do nothing
```

...

```console
PostgresError: duplicate key value violates unique constraint "links_fid_target_fid_type_unique"
```

### Expected Behavior:
The `onLinkAdd` function should gracefully handle conflicts by retaining the existing record in the "links" table when encountering duplicate entries for the "hash" column. In case of a conflict, the function should take no action and proceed with inserting the next record without throwing an error or modifying the existing data.

### Proposed Solution:

1. Modify the onLinkAdd function to gracefully log out the failure.
2. `try { } catch { } finally { }`, however none of the other functions are written this way.

### Environment Details:
Using docker-compose.yml provided.

Node.js version: 20
PostgreSQL version: 15
Operating System: macOS M1/ARM

### Steps to Reproduce:

1. Deploy the provided Docker Compose configuration.
3. Trigger the `onLinkAdd` function with a set of messages that include duplicate values for "hash," "fid," "target_fid," and "type" columns.
4. Observe the logs for the Postgres container to encounter the duplicate key violation error.

**Comment by zachterrell57** [comment]
+1 Also running into this
