### ISSUE TITLE
feat: delegate keys should have application identifiers

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#124]
**What is the feature you would like to implement?**
Allow applications to add an identifier to delegate keys 

**Why is this feature important?**
Allows applications to parse messages in different ways and prioritize or deprioritize content from certain other applications.

**Will the protocol spec need to be updated??**
Signer secction will need to be updated

**How should this feature be built? (optional)**
TBD

**Additional context**
TBD

**Comment by pfletcherhill** [comment]
#### Proposed update to SignerAdd message
```
type SignerAddBody = {
  delegate: string;
  meta?: string; // 25 character limit 
}
```

Does that address this ticket, or are we looking for something more?

**Comment by varunsrin** [comment]
some suggestions: 

1. would prefer call it something specific like appId instead of meta, given that its purpose is specific 
2. might be useful to introduce lightweight namespacing syntax which would allow a company to have multiple identifiable apps (e..g purpleapp.ios) (purpleapp.desktop). could be as simple as respecting periods as namespace delimiters and grouping from left to right. 
3. is 25 chars the right size? based on our transport protocol does it make sense to have a rounded byte size?

**Comment by pfletcherhill** [comment]
I was imagining meta could be used for more than strictly an app ID, like how we're adding meta to casts to include arbitrary extra data. It could be:
* string with a nickname the user assigns to the key when they create it
* string with the name of the app it was created for
* Stringified JSON with name and URL of app

No strong opinion about size. Maybe 16 bytes?

**Comment by varunsrin** [comment]
moving to 2.1.0 per our discussion

**Comment by sds** [comment]
Given we now allow a `name` in the `SignerAdd` message, can this ticket be closed? 

Or is this referring to a different desired feature?

**Comment by varunsrin** [comment]
it's a different feature, but let's close for now. this is the kind of change that should go through the new FIP process.
