### ISSUE TITLE
bug: github does not automatically publish docker image for a new release

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#1288]
**What is the bug?**
The workflow to publish the image is not reliably picking up new releases: https://github.com/farcasterxyz/hub-monorepo/actions/workflows/publish.yml. 

Investigate why and fix.

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by Huge** [comment]
I have inspected it looking at https://github.com/farcasterxyz/hub-monorepo/actions/runs/6114821357 and https://hub.docker.com/r/farcasterxyz/hubble/tags

and it seems working fine, this ticket should be closed now.

**Comment by sds** [comment]
This was working for the recent 1.5.6 and 1.6.0 releases.
