### ISSUE TITLE
feat: REST API for Hub

### ISSUE THREAD

**Issue by adityapk00** [farcasterxyz/hub-monorepo#1295]
## **Motivation**

Our Hubs currently operate using a gRPC API. While gRPC is efficient, it presents several challenges:

1. It's difficult and non-intuitive to use.
2. Constructing protobufs for query arguments can be cumbersome.
3. The API isn't universally accessible, especially from browsers.

This proposal suggests implementing a REST API for the hubs. The advantages of a REST API include:

1. They can be easily accessed from various platforms, including browsers and using tools like **`curl`**.
2. No additional dependencies (like protobufs) are needed to interact with them.
3. They are simpler to understand, deploy, and debug.

### **Implementation Details:**

1. The REST API will coexist with the current gRPC API and will be served on a new port (2181).
2. The REST API will internally call the gRPC API, ensuring consistent data returns. The REST API will not introduce any additional business logic. gRPC responses will be automatically converted to JSON using **`protobufjs`**, which is already part of our stack.
3. Errors will also be presented as plain JSON objects. Callers are expected to parse the JSON to extract error details. Additionally, HTTP response codes will be set to reflect the nature of the error.

## **Differences from the gRPC API**

- These APIs will be NOT be available in the REST API
    - Admin API
    - Sync Methods
- The "Bulk" methods in gRPC are integrated into standard endpoints in the REST API (for instance, bulk requests for casts can be made from the **`/casts`** endpoint).
- We won’t implement the `subscribe` method to get Hub events.

## **Pros & Cons:**

**Pros:**

- REST is more intuitive and easier to understand, invoke, deploy, debug, and consume.
- Protobufs returned will be automatically converted to JSON, simplifying the REST server implementation. By calling the gRPC API internally, both APIs will inherently remain consistent.

**Cons:**

- JSON responses can be verbose, leading to increased network overhead.
- There will be a need to maintain and synchronize documentation between the REST and gRPC APIs.
- No push mechanism, so users will be expected to poll for Hub events (i.e, no direct replacement for the gRPC’s `subscribe` method)

## **API Specification:**

- Except for the **`/message`** endpoint (which uses POST), all API calls are made with the GET method.
- The API returns plain JSON objects. When multiple objects are to be returned, they are encapsulated within arrays.
- Endpoints returning multiple objects support pagination:
    - **`pageSize`** and an optional **`nextPageToken`** can be provided.
    - Responses include a **`nextPageToken`** for fetching subsequent pages. If this token is undefined, no more pages are available.
    - Objects returned are usually sorted. To reverse the sort order, use **`reverse=1`**.
- Various endpoints accept filters such as **`link_type`** or **`target_fid`** as URL parameters. Multiple filters can be applied concurrently, and they are processed sequentially.
- Endpoints are prefixed with the API version number, **`v1`**. For instance, the endpoint to submit a message is **`/api/v1/message`**.

**Submit Methods**:

- **`POST /message`**
    
    Post data: Any message object as JSON
    

**Event Methods**:

- **`GET /event/:id`**
    
    Get a particular Event by Id
    
- **`GET /events?from=id`**
    
    Get all events starting at event ID. 
    
    Returns a `nextEventId` which can be used to page through the events
    

**Casts**:

- **`GET /cast/:fid/:hash`**
    
    Get cast by fid and hash
    
- **`GET /casts/:fid`**
    
    Get all casts by FID
    
- **`GET /casts/parent/:fid/:hash`**
    
    Get all casts for the parent castID
    
- **`GET /casts/parent/:url`**
    
    Get all casts by the parent URL
    
- **`GET /casts/mention/:fid`**
    
    Get all casts that mention the FID
    

**Reactions**:

- **`GET /reaction/:fid/:hash`**
    
    Get reaction by fid and message hash
    
- **`GET /reactions/:fid?type=<reaction_type>`**
    
    Get all reactions by the FID, filtered by reaction type
    
- **`GET /reactions/target/:fid/:hash?type=<reaction_type>`**
    
    Get all reactions for the target Cast (authored by FID and the hash of the target cast)
    
- **`GET /reactions/target/:url?type=<reaction_type>`**
    
    Get all reactions for the target URL
    

**Links**:

- **`GET /links/:fid?type=<link_type>&target_fid=<target_fid>`**
    
    Get all links for the FID, filtered by link type and target FID
    
- **`GET /links/target?type=<link_type>&target_fid=<target_fid>`**
    
    Get all links for the target FID, filtered by link type.
    

**User Data**:

- **`GET /userdata/:fid?type=<user_data_type>`**
    
    Get all UserData for fid, optionally filtered by the user data type
    
- ~~`GET /nameregistryevent/:name`~~
    
    ~~Get the Name registry event for the given name~~
    
    Will be deprecated for OP Mainnet
    

**Username Proof**:

- **`GET /usernameproof/:name`**
    
    Get User name proof by name
    
- **`GET /usernameproofs/:fid`**
    
    Get all user name proofs by FID
    

**Verifications**:

- **`GET /verifications/:fid?address=<address>`**
    
    Get all verifications for the fid, filtered by the given address
    

**Signer**:

- ~~`GET /signer/:fid?signer=<signer>`~~
    
    ~~Get all signers for the fid, optionally filtered by the signer address~~
    
    Will be deprecated on OP Mainnet
    

**OnChain Events**:

- **`GET /onchain/signer/:fid?signer=<signer>`**
    
    Get all onchain signers for the FID, optionally filtered by the signer address
    
- **`GET /onchain/events/:fid?type=<event_type>`**
    
    Get all onchain events for the FID, optionally filtered by the event type
    
- **`GET /onchain/idregistryevent/:address`**
    
    Get an onchain id registry event by address
    

- **`GET /idregistryevents/:fid`**
    
    Get all ID registry events for the given fid
    
- **`GET /idregistryevents/:address`**
    
    Get all ID registry events for the given address
    

**Storage**:

- **`GET /storagelimits/:fid`**
    
    Get the storage limit for the given FID

**Comment by hellno** [comment]
I love this 🙌🏼 I was unfamiliar with grpc and was really struggling, this would make onboarding new devs easier

**Comment by adityapk00** [comment]
This is live in 1.5.6
