### ISSUE TITLE
bug: Hubble does not process multiple Signer Adds in the same tx correctly

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1308]
**What is the bug?**
During migration, we noticed that Hubble will only accept the first Signer added in a transaction and ignore the rest. The issue is due to a bug where the txIndex is used to dedupe events instead of the logIndex. We should cut a patch release with this as soon as it is ready and encourage upgrades.

**Comment by Aramesh1977** [comment]
great
