### ISSUE TITLE
bug(hubble): setup script still asks for goerli rpc url 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1310]
**What is the bug?**
Hubble no longer tracks Goerli, but the setup script asks to provide a Goerli RPC URL

**How can it be reproduced? (optional)**
`rm -rf ~/hubble` run `curl -sSL https://download.thehubble.xyz/bootstrap.sh | bash`

**Comment by adityapk00** [comment]
Fixed in https://github.com/farcasterxyz/hub-monorepo/pull/1318
