### ISSUE TITLE
chore: Improved documentation for running web grpc proxy, statsd & grafana in the install from source section

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1324]
**What is the feature you would like to implement?**
Add documentation for running web grpc proxy, statsd & grafana in the install from source section

https://www.thehubble.xyz/intro/install.html

**Why is this feature important?**
To help developers looking to make improvements to hubble

**Will the protocol spec need to be updated??**
No

**Comment by varunsrin** [comment]
@manan19 instructions for grafana are here: https://www.thehubble.xyz/intro/monitoring.html

what in particular about statsd is misisng?

**Comment by manan19** [comment]
@varunsrin i was looking for how to configure statsd when running Hubble from source.

Spinning up the docker configurations of envoy, statsd and grafana alongside running hubble from source doesn’t work.

**Comment by sds** [comment]
Looks like there are now instructions for how to use statsd via Docker Compose when running Hubble from source in https://www.thehubble.xyz/intro/monitoring.html. Closing.
