### ISSUE TITLE
bug (replicator): Reintroduce the (fid, signer) uniqueness constraint

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1325]
**What is the bug?**
There are duplicate rows in postgres for a signer with the same fid and signer public key 

**How can it be reproduced? (optional)**
Run replicator to full sync and restart a few times using another hub

**Additional context (optional)**
Constraint was added and then dropped temporarily to unblock migration. https://github.com/farcasterxyz/hub-monorepo/pull/1298. The migration requires an operation on the signers table that combines multiple rows into a single row that represents the current state of the signer before the constraint can be applied to the table again.

**Comment by manan19** [comment]
cc @sanjayprabhu

**Comment by sds** [comment]
This constraint is re-introduced in the new replicator app in #1462.
