### ISSUE TITLE
getUserNameProofsByFid is not returning all fnames associated with Fid

### ISSUE THREAD

**Issue by chetankashetti** [farcasterxyz/hub-monorepo#1326]
**What is the bug?**
All the fnames are not being returned for an fid using getUserNameProofsByFid

**How can it be reproduced? (optional)**
call getUserNameProofsByFid with an Fid, limited fnames will be returned

**Additional context (optional)**
Hub version: 1.5.1

For example, for an fid 602 there are three fnames associated.

when i query getUserNameProofsByFid it reurns only two. 
Ideally it should return 3 fnames.

example 2: for Fid 2 also there are two fnames.
but we receive only one in the above method call.

Sample code: 
```
const hubRpcEndpoint = "";
const client = getInsecureHubRpcClient(hubRpcEndpoint);

client.$.waitForReady(Date.now() + 5000, async (e) => {
  if (e) {
    console.error(`Failed to connect to ${hubRpcEndpoint}:`, e);
    process.exit(1);
  } else {
    console.log(`Connected to ${hubRpcEndpoint}`);
    const fid = 2;
    getUsernameProofs(fid)
   client.close();
  }
});

async function getUsernameProofs(fid: number) {
    let result = await client.getUserNameProofsByFid({ fid });
    if (result.isErr()) {
      throw new Error("Unable to backfill", { cause: result.error });
    }
    const usernameProofs = result.value;
    const hubMessages: HubMessage[] = []
    for (const proof of usernameProofs.proofs) {
           console.log(Buffer.from(proof.name).toString("utf-8").replace(/\0/g, ""))
           console.log(bytesToHexString(proof.owner)._unsafeUnwrap())
           console.log(proof.type.toString())
    }
}



```

**Comment by sanjayprabhu** [comment]
@chetankashetti I'm seeing the right number of proofs on my hub:
```
34.125.44.148:2283 hub> (await rpcClient.getUserNameProofsByFid({fid: 2})).value.proofs.map((p) => p.name.toString('utf-8'))
[ 'v', 'varunsrin.eth' ]
34.125.44.148:2283 hub> (await rpcClient.getUserNameProofsByFid({fid: 602})).value.proofs.map((p) => p.name.toString('utf-8'))
[ 'betashop', 'betashop.eth', 'jasongoldberg.eth' ]
```


Could you post the response from `rpcClient.getInfo({dbStats: true})`? That would tell us if you're missing fname events. You could fix that by restarting the hub with `--resync-name-events`

**Comment by chetankashetti** [comment]
@sanjayprabhu  This is the response i am getting from hub for stats 
```Fetching messages from hub  (~{"value":{"version":"1.5.1","isSyncing":false,"nickname":"Farcaster Hub","rootHash":"07bb1de87424eb5a35a5209121212a9ea4b34122","dbStats":{"numMessages":3827541,"numFidEvents":16837,"numFnameEvents":4042}}} messages)```


Meanwhile let me try the command mentioned.

**Comment by sanjayprabhu** [comment]
Yeah, you're missing a lot of fname events, you should have a similar number as the fidEvents.

**Comment by chetankashetti** [comment]
Thank you for the quick response. :) 

so the command will fix the issue, we receive all fnames by  ```getUserNameProofsByFid``` method.
Just confirming

**Comment by sanjayprabhu** [comment]
Yes, it should fix the issue. See https://github.com/farcasterxyz/hub-monorepo/issues/1045 for a longer term fix for this (so hubs can detect and fix this themselves)

**Comment by chetankashetti** [comment]
restarting with flag resolved issue. Thanks @sanjayprabhu

**Comment by chetankashetti** [comment]
we will follow #1045 for long term fix
