### ISSUE TITLE
test(hubble): acquiring storage units

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1332]
**What is the test you would like to implement?**
Acquire a storage unit for an account in production and verify that messages are not pruned when the limits are exceeded.

**Comment by varunsrin** [comment]
@sanjayprabhu did you already verify this with your test? or should i do this one more time to make 100% sure?

**Comment by sanjayprabhu** [comment]
The limits are correct:

```
[
  { storeType: 1, limit: 15000 },
  { storeType: 2, limit: 3750 },
  { storeType: 3, limit: 7500 },
  { storeType: 4, limit: 150 },
  { storeType: 6, limit: 15 },
  { storeType: 5, limit: 75 }
]
```

but I haven't actually exceeded them. So, can't hurt to do it on your account.

**Comment by varunsrin** [comment]
Storage unit was rented in this transaction: https://optimistic.etherscan.io/tx/0x78b5fc6db8e5a31f72ad33c4a0ed3957d49ba46ac38065855a860ed382ee2d50

@sanjayprabhu assigning back to you for verification, we could manually have tony rebroadcast my previously pruned messages from the warpcast db to verify that the newlimits are active.

**Comment by sanjayprabhu** [comment]
```
nemes.farcaster.xyz:2283 hub> res = await rpcClient.getCurrentStorageLimitsByFid({fid: 2})
Ok {
  value: {
    limits: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  }
}
nemes.farcaster.xyz:2283 hub> res.value.limits
[
  { storeType: 1, limit: 15000 },
  { storeType: 2, limit: 7500 },
  { storeType: 3, limit: 7500 },
  { storeType: 4, limit: 150 },
  { storeType: 6, limit: 15 },
  { storeType: 5, limit: 75 }
]
```

New limits look good, we'll replay the links messages and close tomorrow.
