### ISSUE TITLE
chore(hubble): enable debug logs for fc operated hubs 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1333]
**What is the feature you would like to implement?**
Enable debug logs in production for the three fc operated hubs.

**Why is this feature important?**
The lack of merge events, which are in debug logs, make it hard to investigate issues in production.

**Comment by sanjayprabhu** [comment]
After some investigation, decided this would be way too much log volume, most of it being useless. Now that we have grafana as the primary user visibility system (and docker pruning logs), I think we should move the individual logs lines we switched to debug back to info and close this. Will fix.
