### ISSUE TITLE
docs: outdated documentation for commands

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1337]
Documentation in https://www.thehubble.xyz/docs/cli.html is lagging cli.ts. In particular: 

- [x] L2: Document all L2 options, remove duplicated docs from Ethereum section
- [x] Networking: document denied peers 
- [x] Metrics: document statsd command, move gossip metrics here
- [x] Deprecate yarn status from docs (and separately, as a command) 
- [ ] Debug: Deprecate the fnr address option in debug, remove from hubble (also consider deprecating it from hubble) 
- [x] Debug:Document disable-console-status option in debug
- [ ] Document the profile / storage command (what is this used for?)
- [ ] Document events-reset command

**Comment by varunsrin** [comment]
@adityapk00 and @sanjayprabhu assigning this to both of you since you each own different commands here and have the best context for making calls on what is safe to be deprecated/ should be updated.

**Comment by adityapk00** [comment]
I fixed these, and I also added a linter to make sure all CLI options have helptext

https://github.com/farcasterxyz/hub-monorepo/pull/1353
