### ISSUE TITLE
docs(www): add tutorial for making a signer + casting from it

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1348]
**What is the feature you would like to implement?**

An end-to-end tutorial for making a cast and broadcasting it into a Hubble instance. Would require setting up a signer and then making the cast, so maybe they can be separate tutorials that link to each other.

**Comment by sanjayprabhu** [comment]
https://github.com/farcasterxyz/hub-monorepo/pull/1511
