### ISSUE TITLE
docs(www): add tutorial to read a users profile information, recent casts and recent follows 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1350]
**What is the feature you would like to implement?**
An end-to-end tutorial showing how to read someones profile information, recent casts and recent follows. Ideally using Hub's new REST APIs instead of the gRPC ones.

**Comment by sanjayprabhu** [comment]
https://github.com/farcasterxyz/hub-monorepo/pull/1511

**Comment by sanjayprabhu** [comment]
Whoops, close wrong issue. Re-opening

**Comment by sanjayprabhu** [comment]
We could update the [chronological feed](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-nodejs/examples/chron-feed/index.ts) example to use the http API. is that what you had in mind?

**Comment by sds** [comment]
We have a tutorial for getting UserData [here](https://docs.farcaster.xyz/developers/guides/querying/fetch-profile), and a tutorial for getting messages (casts specifically) [here](https://docs.farcaster.xyz/developers/guides/querying/fetch-casts), but this is easily generalized to other message types.
