### ISSUE TITLE
bug: (hubble) Envoy proxy isn't running after ./hubble.sh upgrade

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1362]
**What is the bug?**
Envoy proxy doesn't run as expected

Hubble 1.5.2 pulls envoy, but doesn't run the container.

When I tried running it directly via docker-compose up -d envoy, got the following error

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/ec2-user/hubble/envoy/envoy.yaml" to rootfs at "/etc/envoy/envoy.yaml": mount /home/ec2-user/hubble/envoy/envoy.yaml:/etc/envoy/envoy.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

`/home/ec2-user/hubble/envoy/envoy.yaml` is a directory instead of a yaml file

**How can it be reproduced? (optional)**
`./hubble.sh upgrade`

**Comment by adityapk00** [comment]
Sorry, it was a bug in the script. It will be fixed in the next version, but in the meanwhile, you can:

```
cd ~/hubble
sudo mkdir envoy && sudo chmod +rx envoy && cd envoy
sudo curl -sS -o envoy.yaml https://raw.githubusercontent.com/farcasterxyz/hub-monorepo/@latest/apps/hubble/envoy/envoy.yaml
```

Now you should be able to start the envoy docker container.
