### ISSUE TITLE
bug: message divergence between synced hubs

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1380]
**What is the bug?**
Looking at message counts across synced hubs, there is a variance of ~ 100k messages. Some of this might be due to bugs in earlier versions like 1.5.0. Before the 1.6 release we should attempt to get to a state where all known hubs are fully in sync with a divergence of < 10k messages.

**Comment by Behnaming** [comment]
its so complicated i just dont understand it
