### ISSUE TITLE
jq throws error during script install/upgrade

### ISSUE THREAD

**Issue by vrypan** [farcasterxyz/hub-monorepo#1395]
**What is the bug?**
During the script install (or upgrade, using `./hubble.sh upgrade`) jq throws the following error. The installation moves on, but Grafana has to be manually configured.

> jq: error (at <stdin>:0): Cannot iterate over number (400) 
> parse error: Invalid numeric literal at line 1, column 8

**How can it be reproduced? (optional)**
I get it every time I run the install script. 

> System: Raspberry Pi 4 (8GB RAM)
> `uname -a: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
> jq version: jq-1.6

**Additional context (optional)**

<img width="486" alt="Screenshot 2023-09-19 at 21 04 46" src="https://github.com/farcasterxyz/hub-monorepo/assets/58812/0a1986c2-3b9a-495d-92e4-72c6032539ee">

**Comment by adityapk00** [comment]
I think the version of `jq` on this distro might be too old. Can you please do `jq --version`?

**Comment by adityapk00** [comment]
I fixed this particular issue, but note that this still won't work yet. Because I think raspberry pi reports its platform as linux/arm/v8, but we only publish linux/arm64 images. You might have to expliticly pull the docker image
```
 sudo docker pull farcasterxyz/hubble:latest --platform linux/arm64
```

**Comment by vrypan** [comment]
I'm not sure if this helps, but other than the jq error above (which I think it only affects the Grafana configuration and does not cause the hubble.sh to exit), the hub installs, runs and upgrades just fine.
