### ISSUE TITLE
feat: (replicator) Index channel metadata when a new channel is found

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1399]
**What is the feature you would like to implement?**
Index channel metadata when a new channel is found

**Why is this feature important?**
1. Developers need to use manually updated solutions like [this](https://github.com/neynarxyz/farcaster-channels)

2. Easier to read dashboards for channel data like [this one](https://data.hubs.neynar.com/public/dashboards/U6aGGq6CQOZXIx6IO71NbaUFDMwX14nYs0OyhT88?org_slug=default)

**Will the protocol spec need to be updated??**
No changes are needed to the protocol

**How should this feature be built? (optional)**
An example implementation of how Opencast is scanning for channel metadata 
https://github.com/stephancill/opencast/blob/main/src/lib/topics/resolve-topic.ts

h/t @stephancill 

For RPC providers, we could potentially use a list of RPC providers on this page for well-known chains. https://www.alchemy.com/chain-connect

**Comment by sds** [comment]
Channels are not yet defined in any FIP. We should wait until their definition is formally specified in an FIP.

Or is this ticket suggesting any cast with a URL as a parent (rather than another cast) is automatically a channel? (but perhaps without an accompanying image, etc.)

**Comment by sds** [comment]
Will include this as part of the FIP once channels are solidified from a product perspective.
