### ISSUE TITLE
bug: (replicator) Replicator doesn't delete pruned data from the protocol, only marks the messages table

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1401]
**What is the bug?**
The replicator doesn't delete data that has been pruned by the hubs.

**How can it be reproduced? (optional)**
Run the replicator, see the prune messages come, check the casts or links table.

**Additional context (optional)**

> We would need to add logic like what we do in onMergeMessages, where if the operation is delete/prune/revoke, we call the corresponding on*Remove method
from @sds 

By default, the replicator should delete pruned data but it would be good to introduce a "do not prune" mode as a parameter into the replicator so that people can run archival or data recovery services for users that might have mistakenly forgotten to pay for additional storage units.

**Comment by sds** [comment]
The new replicator app now marks derived data as soft-deleted when the corresponding message is pruned/revoked/deleted.

You can hard delete the data by hard deleting the message. This will cause derived data to be deleted via foreign key cascading deletes.
