### ISSUE TITLE
bug: (replicator) Replicator crashes with "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"

### ISSUE THREAD

**Issue by wojtekwtf** [farcasterxyz/hub-monorepo#1407]
**What is the bug?**
I was setting up hub postgres replicator with AWS and encountered the following bug in the process
<img width="1214" alt="Screenshot 2023-09-20 at 12 58 01" src="https://github.com/farcasterxyz/hub-monorepo/assets/10712818/abf89216-1157-4241-a2ee-0de073eec4e4">

I temporarily solved it with running `export NODE_OPTIONS="--max-old-space-size=8192"` but i cannot guarantee it actually works since it encountered another problem later in the process.

Before failing, the process managed to sync around 700k casts.

**How can it be reproduced? (optional)**
I ran the process using `yarn install` / `yarn start` path, on an AWS EC2 instance, `m5.large` type, running Ubuntu. It has 8GiB of RAM. The db im using is AWS RDS postgres instance `db.t3.small` type. It has 2 Gib of RAM.

I ran it on a repo with last commit 520843baf49738de00591f0c7f5a3bea90b7e4f2

**Comment by dylsteck** [comment]
I can confirm that I've run into this bug as well(sharing logs from Railway). I've tried changing the MAX_PAGE_SIZE in `hubReplicator.ts` but it hasn't helped much.

<img width="840" alt="Screenshot 2023-09-20 at 5 43 08 PM" src="https://github.com/farcasterxyz/hub-monorepo/assets/12853808/3d56c482-c183-479e-ac88-8c3e3ea33ac2">

**Comment by sds** [comment]
Thanks for the report. Is this happening consistently each time you start the replicator example?

**Comment by dylsteck** [comment]
For myself it's not happening each time I start the replicator example, but randomly during deployed instances(this has happened about one in every ten deployments if not a little more frequently).

**Comment by zachterrell57** [comment]
+1, also get this error inconsistently

**Comment by sds** [comment]
The new replicator application likely fixes this, but if you are able to reproduce with that new application let's open a new ticket. Thank you!
