### ISSUE TITLE
bug: (replicator) Replicator crashes with "PostgresError: deadlock detected"

### ISSUE THREAD

**Issue by wojtekwtf** [farcasterxyz/hub-monorepo#1408]
**What is the bug?**
I was setting up hub postgres replicator with AWS and encountered the following bug in the process
<img width="1214" alt="Screenshot 2023-09-20 at 13 11 00" src="https://github.com/farcasterxyz/hub-monorepo/assets/10712818/7a006b31-71fd-42fd-b4bb-e04a8d28d1f4">

Before crashing, the process synced correctly few thousands of casts

**How can it be reproduced? (optional)**
I ran the process using `yarn install` / `yarn start` path, on an AWS EC2 instance, `m5.large` type, running Ubuntu. It has 8GiB of RAM. The db im using is AWS RDS postgres instance `db.t3.small` type. It has 2 Gib of RAM.

I ran it on a repo with last commit 520843baf49738de00591f0c7f5a3bea90b7e4f2

**Comment by sds** [comment]
Thanks for the report. Is this consistent each time you start the replicator?

**Comment by sds** [comment]
The new replicator application likely fixes this, but if you are able to reproduce with that new application let's open a new ticket (since that app should have a better stack trace than the example app).
