### ISSUE TITLE
bug(hubble): signers are out of sync on some hubs

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#1425]
**What is the bug?**
Fid 6546 has a signer missing on a lot of hubs:
```
invalid signer: signer 0x9e49829443c9a11aeb283b06a773d206689978ff21cdbd3f2bbb2931c64f38b7 not found for fid 6546
```

Nemes has some additional fids where it's missing signers, e.g. 
```
invalid signer: signer 0xd697997bfee1112f733cafc18251c09d324a085fceb9e17ccfef7bc52f6e3eaa not found for fid 762
```

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by artlu99** [comment]
this is my FID. Happy to help triage as this appears to be blocking me in multiple places. pls DC @artlu.eth on Warpcast thank you 🙏
