### ISSUE TITLE
feat: smart contract wallet verifications

### ISSUE THREAD

**Issue by horsefacts** [farcasterxyz/hub-monorepo#1437]
**What is the feature you would like to implement?**
Extend verifications to support EIP-1271 signatures from smart contract wallets. See also: https://github.com/farcasterxyz/protocol/discussions/109

**Why is this feature important?**
Support linking smart contract wallets and other non-EOA accounts to Farcaster identities.

**Will the protocol spec need to be updated??**
Yes: Section 1.5 — [Verifications](https://github.com/farcasterxyz/protocol/blob/main/docs/SPECIFICATION.md#15-verifications)

**Comment by sds** [comment]
Implemented in #1449.
