### ISSUE TITLE
Installation Error on Node 20: spawn node-gyp ENOENT

### ISSUE THREAD

**Issue by PirosB3** [farcasterxyz/hub-monorepo#1440]
**What is the bug?**

When trying to add the `@farcaster/hub-nodejs` package using Yarn using Node v20.5.1, I encountered the following error:

```
yarn add @farcaster/hub-nodejs

yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/3] ⠄ ref-napi
[-/3] ⠄ waiting...
error /Users/danielpyrathon/Desktop/Projects/farcaster-stuff/node_modules/ref-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/danielpyrathon/Desktop/Projects/farcaster-stuff/node_modules/ref-napi
Output:
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v20.5.1
```

Upon switching to v18.17.1 (via nvm) the issue disappears.
I am on MacOS Ventura (Apple M1 Pro). I installed my node via `nvm`

### Run yarn add @farcaster/hub-nodejs on v20.5.1
Expected Behavior:
The package should be added successfully.

### Actual Behavior:
Encountered an error related to node-gyp.

Let me know how I can help! and thanks for your support. I'm not blocked in any way since i can simply develop using Node 18.

**Comment by sds** [comment]
FWIW I'm not able to reproduce this with Node 20.5.1 on my machine (macOS Ventura 13.5.2).

However, based on the error it looks like you might not have Python installed on your system, or NPM is unable to find it. You can find some suggestions of how to resolve in [this thread](https://github.com/nodejs/node-gyp/issues/277#issuecomment-261863503), but I'm going to close since I'm unable to reproduce.
