### ISSUE TITLE
feat(hubble): number of hub peers in info http api

### ISSUE THREAD

**Issue by jgresham** [farcasterxyz/hub-monorepo#1445]
**What is the feature you would like to implement?**
Hub operators want to know the number of peers that their hubble is connected to. 

**Why is this feature important?**
This helps for monitoring the effectiveness and health of a hub.

**Will the protocol spec need to be updated??**
I don't think so

**How should this feature be built? (optional)**
Add a `peers` key to the info api (https://www.thehubble.xyz/docs/httpapi/info.html#info) with a value of the number of peers or a list of peer-ids from libp2p

**Additional context**
Ethereum clients implement peer apis (ex. https://ethereum.github.io/beacon-APIs/#/)
<img width="461" alt="Captura de pantalla 2023-10-02 a la(s) 3 00 47 p m" src="https://github.com/farcasterxyz/hub-monorepo/assets/3721291/42db0d0f-4a5c-4cd2-8961-d9f5114888c6">

**Comment by sds** [comment]
Thanks for the suggestion! 

We now have a dedicated endpoint for this: https://www.thehubble.xyz/docs/httpapi/currentpeers.html
