### ISSUE TITLE
feat: Sign in With Farcaster Hub API 

### ISSUE THREAD

**Issue by horsefacts** [farcasterxyz/hub-monorepo#1457]
**What is the feature you would like to implement?**
Hub APIs for [Sign in With Farcaster](https://github.com/farcasterxyz/protocol/discussions/110)

**Why is this feature important?**
A dependency of the full Sign in With Farcaster workflow.

**Will the protocol spec need to be updated??**
No.

**How should this feature be built? (optional)**
See [Sign in With Farcaster FIP](https://github.com/farcasterxyz/protocol/discussions/110)

**Comment by sds** [comment]
This turned in https://github.com/farcasterxyz/auth-monorepo.
