### ISSUE TITLE
bug: (replicator) embeds should store cast hash as a hex string

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1459]
**What is the bug?**
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/3a76942b-97fd-46f5-8a97-4bbe9ac7fac5)

Embeds using `castId` are being stored as integer array. other spots where bytes are stored, they are in the bytea format but given  that embeds is jsonb and `castId` is inside that json value, might make sense to convert it into it's hex string equivalent.

**How can it be reproduced? (optional)**
```
SELECT * 
FROM casts 
WHERE EXISTS (
    SELECT 1 
    FROM jsonb_array_elements(embeds) AS j(element)
    WHERE j.element->'castId' IS NOT NULL
);
```
looks for these casts^

**Comment by sds** [comment]
This is addressed in #1462 with the new replicator app.
