### ISSUE TITLE
bug: (hubble) Hubble keeps restarting due to an uncaught exception

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1481]
**What is the bug?**
Hub keeps restarting

```
hubble-hubble-1  | {"level":60,"time":1696922553198,"pid":1,"hostname":"0bb438d19400","msg":"Forcing exit after grace period"}
```

```
hubble-hubble-1  | {"level":30,"time":1696922932780,"pid":1,"hostname":"0bb438d19400","msg":"Retrying missing block 108884277 during sync"}
hubble-hubble-1  | {"level":50,"time":1696922932780,"pid":1,"hostname":"0bb438d19400","reason":"Uncaught exception","msg":"shutting down hub"}
```

Reported by another hub runner in the telegram chat

**How can it be reproduced? (optional)**
Run bubble 1.6.0

**Additional context (optional)**
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/40a701dc-d5fc-4c59-9d24-2a0eee36114a)

**Comment by vrypan** [comment]
I'm having the same issue.

**Comment by adityapk00** [comment]
I believe this is the underlying error:
![image](https://github.com/farcasterxyz/hub-monorepo/assets/31996805/0205b179-f162-438a-8a8f-2c9ecf5d031f)

I think this was already fixed in https://github.com/farcasterxyz/hub-monorepo/pull/1465 so this should be out in 1.6.1
cc @sanjayprabhu

**Comment by adityapk00** [comment]
@sanjayprabhu fixed this in 1.6.1

**Comment by Tonyce** [comment]
still restarting after upgrate to 1.6.1

**Comment by Tonyce** [comment]
{"level":50,"time":1697087728496,"pid":1,"hostname":"14cf80c9d7b4","reason":"Uncaught exception","err":{"type":"Error","message":"This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"Key length exceeded3\".","stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"Key length exceeded3\".","code":"ERR_UNHANDLED_REJECTION"},"msg":"shutting down hub"}

**Comment by sanjayprabhu** [comment]
Yeah, we discovered another variant of the problem. Please update to 1.6.2
