### ISSUE TITLE
bug: userNameProof secondary index is incorrect

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#1501]
**What is the bug?**
From @sds

```
lamia.farcaster.xyz:2283 hub> res = await rpcClient.getUserNameProofsByFid({fid: 3900})
Ok { value: { proofs: [ [Object] ] } }
lamia.farcaster.xyz:2283 hub> res.value.proofs
[
  {
    timestamp: 1696975523,
    name: <Buffer 7a 6f 72 61>,
    owner: <Buffer 0a cf b1 27 05 d3 c6 1e 22 1d 3f 5e 21 37 f3 00 5d 70 22 f9>,
    signature: <Buffer 36 7b ef 02 f0 9b 6b 9f 43 29 5e 6b 2f e4 d8 80 0b 50 6d 07 c0 15 50 c6 79 c9 8c 2e 98 8d b8 a0 62 4c 9d a8 0a fe ad 45 85 a5 21 fb c7 10 91 bb f6 09 ... 15 more bytes>,
    fid: 20910,
    type: 1
  }
]
```

We're not deleting the secondary index for the deleted proof correctly.

Only the API is affected. The hub will not let the fid 3900 set the username because the fid on the proof is actually different, and there is only one proof for this name.

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by sds** [comment]
This has been fixed in #1979.
