### ISSUE TITLE
bug: OOM 

### ISSUE THREAD

**Issue by Tonyce** [farcasterxyz/hub-monorepo#1524]
**What is the bug?**
Seems there is OOM bug

<img width="678" alt="Screenshot 2023-10-16 at 17 00 22" src="https://github.com/farcasterxyz/hub-monorepo/assets/7351139/5a860ca8-d128-44b1-9d00-3bd9f901107c">

**Comment by Tonyce** [comment]
<img width="545" alt="Screenshot 2023-10-16 at 17 02 13" src="https://github.com/farcasterxyz/hub-monorepo/assets/7351139/5c24aa53-5d96-4242-aeef-7d5d95db2fed">

**Comment by sanjayprabhu** [comment]
What version of hubble are you running? Could you try on 1.6.4?

**Comment by sanjayprabhu** [comment]
Fixed in 1.6.5
