### ISSUE TITLE
feat(hubble): gRPC & REST APIs to Get onchain signer by public key

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1567]
**What is the feature you would like to implement?**
New RPC to get on-chain signer by public key

**Why is this feature important?**
In order to verify if a signer add tx has been confirmed on OP mainnet, we need to call warpcast APIs today. Instead, we could be calling our own hub to get this information

**Will the protocol spec need to be updated??**
No

**Comment by sanjayprabhu** [comment]
Hub's don't index this currently and don't have a use case for this. I think external clients should rely on something like the replicator for this information.

**Comment by vrypan** [comment]
Can't you check with OP directly?

**Comment by sanjayprabhu** [comment]
Contracts also don't index by public key. You still need the fid.

**Comment by vrypan** [comment]
If you mean how to get the application who created the signer (not the user who approved it), it's in the key: bytes 64-128 are the fid.
