### ISSUE TITLE
bug: (hubble) userNameProofsByFid is missing username proofs for some fids

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1584]
**What is the bug?**
User has an fname > https://nemes.farcaster.xyz:2281/v1/userNameProofByName?name=healthbot but the fname proof doesn't show up in the fid lookup https://nemes.farcaster.xyz:2281/v1/userNameProofsByFid?fid=8304

fname proofs show up for some other users https://nemes.farcaster.xyz:2281/v1/userNameProofsByFid?fid=2

**How can it be reproduced? (optional)**
Run a hub, call the APIs above. Seems to affect all hubs

**Comment by vrypan** [comment]
Same for FID=19150

**Comment by sanjayprabhu** [comment]
Could be related to https://github.com/farcasterxyz/hub-monorepo/issues/1501. Will investigate.

**Comment by manan19** [comment]
@sanjayprabhu any updates on this one? Which API is showing the inaccurate information?

**Comment by sds** [comment]
We believe this was addressed in #1979. If you're still seeing this issue after upgrading Hubble to 1.12.2 or newer, let us know!
