### ISSUE TITLE
feat (hubble): Implement a way to have fallback for RPC providers

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1598]
**What is the feature you would like to implement?**
RPC providers fail from time to time, it would be good to have a fallback RPC provider in the env and have hubble try the fallback after a few failures from the main one.

**Why is this feature important?**
Improves hub reliability

**Will the protocol spec need to be updated??**
No

**Comment by lazyfuhrer** [comment]
Can I work on this @manan19 ?

**Comment by manan19** [comment]
Go for it! I’m not a maintainer

**Comment by sanjayprabhu** [comment]
Both the RPC url params for hubble support a comma separated list. If multiple urls are provided, the rest will be used as fallback. This should work with the env vars as well.

**Comment by manan19** [comment]
> Both the RPC url params for hubble support a comma separated list. If multiple urls are provided, the rest will be used as fallback. This should work with the env vars as well.

@sanjayprabhu does the fallback work while the hub is already up and running or is the fallback only accounted for when the hub is doing the startup checks?

**Comment by sanjayprabhu** [comment]
This should work all the time.
