### ISSUE TITLE
bug(replicator): user_data table values are missing an update

### ISSUE THREAD

**Issue by masato25** [farcasterxyz/hub-monorepo#1603]
**What is the bug?**

I'm running my replicator node (v0.2.5) and encountered an issue with updating user data

In this API, the USER_DATA_TYPE_DISPLAY for fid 3103 is 'Aunthomie'.
https://nemes.farcaster.xyz:2281/v1/userDataByFid?fid=3103
but the display name in the replicator database table is still 'Homie'.

I can locate the correct event update in the message table, just like the screenshot below
![image](https://github.com/farcasterxyz/hub-monorepo/assets/4387822/d2c1a998-4e2e-4777-bd25-44f6aa381965)
as shown in the screenshot below, it seems that the 'updated_at' time is quite close to the message event above
![image](https://github.com/farcasterxyz/hub-monorepo/assets/4387822/03fc7fd9-b690-4d7d-8c54-907b81ecb88a)

**Comment by christopherwxyz** [comment]
I am also experiencing this issue. 

https://nemes.farcaster.xyz:2281/v1/userDataByFid?fid=4085 returns the accurate and true data, but my replicator hasn't processed any jobs to update user_data:

<img width="1336" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/362387/c8190c86-3739-4e63-8905-cf0c22d9caff">

yesterday it actually had this data, per this cast:

https://warpcast.com/christopherw.eth/0x97fd5979

**Comment by sds** [comment]
Sorry for the delay in response. We no longer recommend using the replicator. Check out the [Shuttle](https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/shuttle) project if you'd like to sync data to a DB.
