### ISSUE TITLE
feat: Add peercount to logs of Hubble

### ISSUE THREAD

**Issue by anovalunosis** [farcasterxyz/hub-monorepo#1604]
**What is the feature you would like to implement?**
When you execute sudo docker compose logs -f hubble
Currently there is no way to check the peercount.

It would be greate for node runners to have peercount included in the logs:
![image](https://github.com/farcasterxyz/hub-monorepo/assets/128309050/2d66ffe3-ebc0-4b99-bf01-8439b33f31df)

ex. :
**peercount=12**

**Why is this feature important?**
check performance/connectivity of hubble node

**Will the protocol spec need to be updated??**
No

**Additional context**
Ideally the peercount could be printed here:
![image](https://github.com/farcasterxyz/hub-monorepo/assets/128309050/666a597c-98a4-456e-a64b-2f3c65a71cf1)

**Comment by sanjayprabhu** [comment]
The grafana dashboard for hubble shows this information 
![image](https://github.com/farcasterxyz/hub-monorepo/assets/75855/28510354-328d-4a57-a9de-c9e0a91cd139)

See https://docs.farcaster.xyz/hubble/monitoring#monitoring-hubble

**Comment by anovalunosis** [comment]
Thank you!☺️
