### ISSUE TITLE
http info api returns "isSyncing: true" even though the hub seems fully synced

### ISSUE THREAD

**Issue by jgresham** [farcasterxyz/hub-monorepo#1628]
**What is the bug?**
Me and one other user have left our Hubs running for a long time and it seems synced, however, the http info api returns `isSyncing: true`

**How can it be reproduced? (optional)**
Run hubble as a container, let it fully sync (?), disk usage is around 3.7GB (and growing slowly), call the `/info` http api and see the json response which includes `isSyncing: true`

**Additional context (optional)**
I use this api to let hub runners know that their Hub is syncing or fully synced, like so:
![image](https://github.com/farcasterxyz/hub-monorepo/assets/3721291/24ef91e7-d57b-41ba-bd99-94f41ada970b)

**Comment by saez0pub** [comment]
I have tried to resync from scratch but no change, isSyncing is true most of the time.
![Screenshot 2024-02-27 at 11 07 47](https://github.com/farcasterxyz/hub-monorepo/assets/3484146/a48a1126-f80f-4c0b-8177-9f50d26bdd2a)

**Comment by saez0pub** [comment]
grafana seems to show me I have a p2p problem.
Here are some graph (CET time) from 2024-02-28 07:10:00 to 2024-02-28 11:10:00 (from=1709100600000&to=1709115000000)

![Screenshot 2024-02-28 at 11 15 23](https://github.com/farcasterxyz/hub-monorepo/assets/3484146/77392b33-2663-4e03-9fd8-38e14e3dce56)
![Screenshot 2024-02-28 at 11 15 46](https://github.com/farcasterxyz/hub-monorepo/assets/3484146/28abe321-8167-4a6e-a3bc-f02725e61558)

2282 and 2283 ports are open in tcp.

Am i missing something ?
There are so much logs that I'm unable to guess if something important happening, I'm trying to filter on component SyncEngine.

**Comment by sds** [comment]
There might be a misunderstanding about what `isSyncing` means.

Based on what I'm reading in the code, these are the conditions for `isSyncing` to be `true`:

1. Last sync was **not** unsuccessful (https://github.com/farcasterxyz/hub-monorepo/blob/d359ebcdfafdc1fd44c5eaf77700acd74e652519/apps/hubble/src/network/sync/syncEngine.ts#L663)
2. Hub has a peer ID (https://github.com/farcasterxyz/hub-monorepo/blob/d359ebcdfafdc1fd44c5eaf77700acd74e652519/apps/hubble/src/network/sync/syncEngine.ts#L151)

Therefore, we would expect `isSyncing` to usually be true, even if the hub's last sync with its peer didn't result in any changes.

Going to close as not a bug, but feel free to reopen if I've misunderstood the issue. Thanks!

**Comment by jgresham** [comment]
Thanks for the info @sds! Just to confirm, it seems like `isSyncing=true` is a good thing and to be expected.

Some Ethereum node runners might be confused as Eth nodes have a sync API with a different meaning https://www.quicknode.com/docs/ethereum/eth_syncing

**Comment by sds** [comment]
Thanks for the feedback! Looks like you're not alone. Another team member noticed this discrepancy as well and is including a fix in an [unrelated PR](https://github.com/farcasterxyz/hub-monorepo/pull/1833). So stay tuned for when that lands.
