### ISSUE TITLE
New account creation won't allow Continue after entering name and bio

### ISSUE THREAD

**Issue by djscruggs** [farcasterxyz/hub-monorepo#1635]
**What is the bug?**
I have a Farcaster account from a couple years ago and decided to reactivate. After using my seed phrase to recover, I cannot go past the screen to enter name and bio. The Continue button is disabled no matter what I do.

**How can it be reproduced? (optional)**
[Here is a video showing](https://www.loom.com/share/d5950ae840bd4a8e953c7241bfc0a52e?sid=bb879715-df0c-4bbb-bbe1-d49891a5bc84) what happens after I enter the seed phrase and authorize passkeys:

**Additional context (optional)**
This happens on both IOS and Mac OS.

**Comment by Mapsai** [comment]
I can confirm I have the samr issue. This is also reproducible on Android.

**Comment by djscruggs** [comment]
I've since discovered that it's because you have to upload an avatar photo first. There's not indication on the screen that avatar is required.

**Comment by sds** [comment]
Thanks for the report! This issue is specific to Warpcast, so I'll report to that team and close this issue here.
