### ISSUE TITLE
change restart policy for hubble service to always or unless-stopped

### ISSUE THREAD

**Issue by mscurtescu** [farcasterxyz/hub-monorepo#1647]
**What is the bug?**

Currently the restart policy for the `hubble` container is `on-failure:5`, which means that the container is not restarted on either host system or docker restarts. This leads to 3.5 days of down time on average for each restart event, as the upgrade script (which does restart the container) is run by `crontab` once a week.

**How can it be reproduced? (optional)**

- reboot the host system
- notice that the `hubble` container is stopped
- the `statsd` and `grafana` containers are running

**Additional context (optional)**

See: https://docs.docker.com/compose/production/

> Specifying a restart policy like [restart: always](https://docs.docker.com/compose/compose-file/05-services/#restart) to avoid downtime

**Comment by sds** [comment]
Great suggestion. Implemented in #1793.
