### ISSUE TITLE
Unable to access user data using HTTP API call

### ISSUE THREAD

**Issue by harshnambiar** [farcasterxyz/hub-monorepo#1663]
I am trying to call the api from typescript based frontend, and the line in question is: 

`const x = await axios.get(`${server}/v1/castsByFid?fid=${fid}`);`

However, I get a connection refused error. Am I doing something wrong or has this service been revoked? Thanks.

**Comment by christopherwxyz** [comment]
what hub are you using?

**Comment by harshnambiar** [comment]
> what hub are you using?
I don't yet know the farcaster terminology but if you meant the value of _**const server**_ above, then http://127.0.0.1:2281

**Comment by sds** [comment]
Closing due to age. Make sure you're on the latest hub version (1.10.9 at time of writing) and if able to reproduce include the logs from `docker compose logs`. Thank you!
