### ISSUE TITLE
Hub live subscription events tend to miss userdata events specifically `username` event when a new user signs up

### ISSUE THREAD

**Issue by chetankashetti** [farcasterxyz/hub-monorepo#1669]
**What is the bug?**
Hub is subscribed to consume live events like link, userdata, verification address etc. It does not emit username(UserData) event specifically. But it can be queried through hub using ```getUserDataByFidInBatchesOf```.
we're using older version of hubReplicator. 

**How can it be reproduced? (optional)**
Hub Live subscription can reproduce this. we're using 
"@farcaster/hub-nodejs": "^0.10.5" and latest version of the hub.

**Additional context (optional)**
Does the old hubReplicator has missing event issues? I see different implementation of hub replicator.

Not completely sure if its a bug, but we're facing issues with this. Any help here is appreciated. 🙏

**Comment by sds** [comment]
Sorry for the delay in response. 

If you're still seeing this with hub-nodejs 0.11.12 or newer, let us know!
