### ISSUE TITLE
Remove Tests from CI/CD Linting Check

### ISSUE THREAD

**Issue by zachterrell57** [farcasterxyz/hub-monorepo#1679]
**What is the bug?**
We are still checking for updated http docs when making a Hubble PR, even though the docs have moved to a separate repo. Would be best to remove this check and also remove the `www` dir from the hubble folder

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by sds** [comment]
Thanks for raising. Closing in favor of the solution in #1687.
