### ISSUE TITLE
`Docs`: SubmitMessage API redirects to 404

### ISSUE THREAD

**Issue by bitspresso** [farcasterxyz/hub-monorepo#1693]
**Description**
Surfing the official documentation I've been welcomed by 404 page when attempting access [SubmitMessage API](https://www.thehubble.xyz/docs/httpapi/submitmessage.html) section.

![image](https://github.com/farcasterxyz/hub-monorepo/assets/135147216/dc327c99-6d27-4e9e-85fa-eacfba10ce73)

*Related: is the docs repo available publicly?*

**Comment by sds** [comment]
Thanks for the report! Fixed in #1791.
