### ISSUE TITLE
Difficulty syncing replicator

### ISSUE THREAD

**Issue by stephancill** [farcasterxyz/hub-monorepo#1696]
**What is the bug?**
I am running the postgres replicator on the Railway Pro plan. It never completes syncing and eventually gets stuck like in the screenshot below:
<img width="1058" alt="Screenshot 2024-02-04 at 19 46 52" src="https://github.com/farcasterxyz/hub-monorepo/assets/5469870/41d19484-569a-4520-927c-869390941f9f">

**How can it be reproduced? (optional)**
Set up a hub in railway service that uses hub-monorepo with the following env variables with redis and postgres services

```
HUB_HOST=nemes.farcaster.xyz:2283
HUB_SSL=true
NIXPACKS_PKGS=... python3 gcc rustup
NIXPACKS_INSTALL_CMD=yarn install
NIXPACKS_BUILD_CMD=yarn build
NIXPACKS_START_CMD=cd apps/replicator && yarn start
POSTGRES_URL=${{Postgres.DATABASE_URL}}
REDIS_URL=${{Redis.REDIS_URL}}
```

**Additional context (optional)**
After initially getting stuck, restarting the replicator backfills from scratch again, which makes it take even longer. I think snapshot sync would help to at least get faster iteration and feedback loops on the replicator since re-syncing takes a very long time.

**Comment by stephancill** [comment]
Update: managed to sync after removing many of the constraints

**Comment by qbig** [comment]
here is the linked issue mentioned in the cast above: https://github.com/farcasterxyz/hub-monorepo/issues/1556

**Comment by sds** [comment]
Sorry for the delay in response. We don't recommend using the replicator any more due to multiple issues with it. We recommend using the [Shuttle project](https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/shuttle) if you'd like to sync. Thanks!
