### ISSUE TITLE
hubble: Memory consumption increases until hubble gets unresponsive and restarts

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1711]
**What is the bug?**
Hubble's memory consumption increases until it gets unresponsive and restarts

![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/f7229228-3e37-483f-b59e-a6afffd4b457)

![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/547b187e-9eb3-4fd5-9f5e-0a940be30a9e)

**How can it be reproduced? (optional)**
Run hubble

**Additional context (optional)**

**Comment by manan19** [comment]
<img width="611" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/fbc037df-e9ba-45ff-ab71-90654c661b89">
<img width="420" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/26add072-ac7c-4262-82f0-3cb6f3f0c2a1">

The problem has subsided. It also appears to be highly correlated to the incoming gossip

**Comment by manan19** [comment]
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/12890e67-a781-4253-82de-db967cd0d673)
still seeing it, just not as frequent

**Comment by manan19** [comment]
@sds haven't seen it since 2/27
<img width="616" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/df6a16f5-5924-4b21-9f63-c8449a6ab572">

**Comment by manan19** [comment]
although, as mentioned before - it seems correlated with incoming gossip 
<img width="420" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/377624/bd975605-f65e-4e23-af5c-f99ed866e1de">

**Comment by sds** [comment]
Ah, makes sense. I'm going to close since we believe with the [recent min version we pushed out](https://github.com/farcasterxyz/allowlist-mainnet/pull/16/files) we should no longer have floods of gossip messages like we used to. 

Let us know if you see otherwise!

**Comment by manan19** [comment]
We had this happen again earlier today. Hubble ran out of memory and restarted
