### ISSUE TITLE
Hub Error handling non-ts generated message proto

### ISSUE THREAD

**Issue by 0x330a** [farcasterxyz/hub-monorepo#1712]
Trying to submit a new message using non-typescript protobuf generation, gives me an error with invalid hash if I serialize it as `data`, followed [the docs](https://www.thehubble.xyz/docs/messages.html#_1-message) saying to use `data_bytes` instead and that just seems to crash the hub completely

trace is leading here:
https://github.com/farcasterxyz/hub-monorepo/blob/main/apps/hubble/src/storage/db/message.ts#L44C14-L44C46

trace on hub:
```
{"level":50,"time":1708258191280,"pid":1,"hostname":"...","reason":"Unhandled Rejection","err":{"type":"HubError","message":"message data is missing","stack":"HubError: message data is missing
    at makeMessagePrimaryKeyFromMessage (file:///home/node/app/apps/hubble/build/storage/db/message.js:31:15)
    at isMessageInDB (file:///home/node/app/apps/hubble/build/storage/db/message.js:98:57)
    at Hub.submitMessage (file:///home/node/app/apps/hubble/build/hubble.js:910:19)
    at Object.submitMessage (file:///home/node/app/apps/hubble/build/rpc/server.js:413:48)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)","errCode":"bad_request.invalid_param","presentable":false,"name":"HubError"},"msg":"shutting down hub"}
```

**Comment by sanjayprabhu** [comment]
This was fixed in https://github.com/farcasterxyz/hub-monorepo/pull/1722. Let me know if it's still happening. You shouldn't need to pass in `data` if you're sending `data_bytes`.

**Comment by sanjayprabhu** [comment]
We bypass the `isMessageInDB` check (which calls `makeMessagePrimaryKeyFromMessage`) for rpc calls, and we now wrap the `makeMessagePrimaryKeyFromMessage` some error handling. It shouldn't throw anymore I think? But if you see it happening, happy to investigate and fix.

**Comment by sanjayprabhu** [comment]
Your earlier comment made me realize this case will be hit when the message is gossiped out and received by other hubs, but the async wrapping should handle that gracefully.

**Comment by sanjayprabhu** [comment]
Non upgraded Hubble nodes will crash when they receive this gossip message. But upgraded ones should be unaffected.
