### ISSUE TITLE
bug(replicator): updateTableMetrics is using too much postgresql CPU

### ISSUE THREAD

**Issue by saez0pub** [farcasterxyz/hub-monorepo#1763]
**What is the bug?**
the [updateTableMetrics function](https://github.com/farcasterxyz/hub-monorepo/blob/ac861b1236029acbb007456a3f53647d875030d2/apps/replicator/src/hubReplicator.ts#L43) is planned to be called every 5 seconds and each call uses an average of 2.82 minutes of CPU on a gcp 2VCPU / 8 GB RAM instance.
That's not sustainable and a waste of CPU.

**How can it be reproduced? (optional)**
Just start the replicator.

**Additional context (optional)**
I see two possible quick fixes:
* Stop counting the rows if STATSD_HOST is undefined
* Using [estimates](https://wiki.postgresql.org/wiki/Count_estimate) instead of count(*)

Here is the query:
```
SELECT
  (
  SELECT
    COALESCE(COUNT(*), $1) AS "chain_events"
  FROM
    "chain_events") AS "chain_events",
  (
  SELECT
    COALESCE(COUNT(*), $2) AS "fids"
  FROM
    "fids") AS "fids",
  (
  SELECT
    COALESCE(COUNT(*), $3) AS "signers"
  FROM
    "signers") AS "signers",
  (
  SELECT
    COALESCE(COUNT(*), $4) AS "username_proofs"
  FROM
    "username_proofs") AS "username_proofs",
  (
  SELECT
    COALESCE(COUNT(*), $5) AS "fnames"
  FROM
    "fnames") AS "fnames",
  (
  SELECT
    COALESCE(COUNT(*), $6) AS "messages"
  FROM
    "messages") AS "messages",
  (
  SELECT
    COALESCE(COUNT(*), $7) AS "casts"
  FROM
    "casts") AS "casts",
  (
  SELECT
    COALESCE(COUNT(*), $8) AS "reactions"
  FROM
    "reactions") AS "reactions",
  (
  SELECT
    COALESCE(COUNT(*), $9) AS "links"
  FROM
    "links") AS "links",
  (
  SELECT
    COALESCE(COUNT(*), $10) AS "verifications"
  FROM
    "verifications") AS "verifications",
  (
  SELECT
    COALESCE(COUNT(*), $11) AS "user_data"
  FROM
    "user_data") AS "user_data",
  (
  SELECT
    COALESCE(COUNT(*), $12) AS "storage_allocations"
  FROM
    "storage_allocations") AS "storage_allocations"
```
Parameter is `0`.

**Comment by saez0pub** [comment]
The plan:
![Screenshot 2024-03-04 at 09 45 58](https://github.com/farcasterxyz/hub-monorepo/assets/3484146/8b228921-2875-4d79-88bf-48266442ce79)

**Comment by sds** [comment]
Great suggestions! 

* Agree that if there is no STATSD_HOST defined then running this code is pointless
* Also agree that using estimates likely suffices for the purposes of monitoring

Would you be open to submitting a PR?

**Comment by saez0pub** [comment]
Of course 👍 
I have just created https://github.com/farcasterxyz/hub-monorepo/pull/1781
