### ISSUE TITLE
feat: What is the feature you would like to implement?

### ISSUE THREAD

**Issue by DiForss** [farcasterxyz/hub-monorepo#1811]
What is the feature you would like to implement?
Make protobufs/ a subpackage (@farcaster/protobufs) with its own tag versions.

Why is this feature important?
Any third-party library that wants to implement farcaster bindings will have to fetch and parse the protobufs schemas. However, there is no way of knowing the version of the schemas used (and if the ones used by the library are outdated).

The only way to implement something like this now, is to use @farcaster/hubble tags, but this is far from ideal:

Hubble gets new versions even without changes in .proto files (ex. bug fixes/optimizations)
As the protocol becomes more stable and mature, it is reasonable to expect that protobufs schema version changes will be much less frequent than Hubble version changes.

**Comment by sds** [comment]
Thanks for the suggestion. Looks like this was previously proposed in #1518.

Would happily accept a pull request implementing this!
