### ISSUE TITLE
Hubble Link API returns incorrect data

### ISSUE THREAD

**Issue by dawksh** [farcasterxyz/hub-monorepo#1857]
**What is the bug?**
The Hubble [link API](https://docs.farcaster.xyz/reference/hubble/httpapi/links#linkbyid) returns a `400` even if there is a valid link between the provided FIDs. The Link API returns a `200` with data if a link is found else returns a `400`. My app was using this to check if person A followed person B on Farcaster.

**How can it be reproduced? (optional)**
my farcaster account (FID: 2483) follows Dan (FID: 3), the following curl command should return a `200`
```bash
curl https://hub.pinata.cloud/v1/linkById\?fid\=2483\&target_fid\=3\&link_type\=follow | jq
```
instead it returns a 400 error as in the screenshot below:
<img width="810" alt="Screenshot 2024-04-01 at 10 33 19 PM" src="https://github.com/farcasterxyz/hub-monorepo/assets/20741933/638ddf7e-9216-4b7c-8d0a-ac896eb1c9ec">

**Comment by AgadooAgadoo** [comment]
I am seeing the same. E.G. both wake (2904) and I (18513) follow each other.

This returns all my follows including wake
```
/linksByFid?fid=18513
```

This returns all wake's follows including me
```
/linksByFid?fid=2904
```

This returns the same error as dawksh ('Link Add Message not found for 18513' or 2904 if i swap fid/target_fid values in the request). 
```
/linkById?fid=18513&target_fid=2904&link_type=follow returns 
```

**Comment by sanjayprabhu** [comment]
Should be fixed by https://github.com/farcasterxyz/hub-monorepo/pull/1994

**Comment by sds** [comment]
Closing as fixed. Let us know if you're still seeing this issue after upgrading to Hubble 1.12.2. Thanks!
