### ISSUE TITLE
Warpcast signup and support without installing mobile app (android, iOS) - request for OSS APK option

### ISSUE THREAD

**Issue by NukeManDan** [farcasterxyz/hub-monorepo#1862]
> This repository is for the Farcaster protocol, not Warpcast. Closing as not relevant.
> 
> Please use Warpcast's support channel linked in the app for assistance with Warpcast. Thanks!

_Originally posted by @sds in https://github.com/farcasterxyz/protocol/issues/148#issuecomment-2023140772_

Really sorry to ping on it - where can one find the roadmap to OSS of the mobile apps? As I cannot find them in your github org, but assume this is planned. :pray: 

I sadly cannot use warpcast, not connect with support as suggested, until there is a non-apple/google option to use it, and really the app being OSS would be the real way to get started for me.

**Comment by sds** [comment]
Warpcast is a proprietary client that we currently have no near-term plans to open source. If you desire a fully open source client, you'll have to build your own, or perhaps you might find one listed [here](https://github.com/a16z/awesome-farcaster) (**Note: this list is not maintained by Farcaster or Warpcast**).
