### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by dotSaeid** [farcasterxyz/hub-monorepo#1901]
According to the document, I installed Hubble and I also installed the monitoring, the monitoring on port 3000 comes up well.
And I'm on mainnet
All the services on my server are without errors, but I want to test the api, my port 2281 is not responding
It shows the following message
curl: (56) Recv failed: Connection reset by peer
Where do you think the problem lies?

**Comment by sds** [comment]
Hard to know what's wrong without knowing more about your infrastructure. That error indicates the server explicitly closed its side of the connection. Perhaps you have a proxy or load balancer (or the infrastructure provider you're using does) which does not allow communication with port 2281?

Going to close in the meantime.
