### ISSUE TITLE
hubble installation from script - rocksDB failure?

### ISSUE THREAD

**Issue by guyweissman** [farcasterxyz/hub-monorepo#1928]
I'm working on running a hubble hub.

I initially ran one from AWS no problem, and I'm now trying to move to GCP.

I'm using the tutorial presented here: https://www.thehubble.xyz/tutorials/gcp.html

I ran it once with a 60GB instance, and it seemed to be downloading the snapshot until it ran out of disk space.

then i tried a few times with 120GB - and haven't been able to run it since. it always fails on the following error:
Failed to start hub: db.internal_error/IO error: No such file or directory: while open a file for lock: .rocks/rocks.hub._default/trieDb/LOCK: No such file or directory

Error: Failed to start hub\\n    at file:///home/node/app/apps/hubble/src/cli.ts:689:14\\n    at /home/node/app/node_modules/neverthrow/dist/index.cjs.js:113:102\\n    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:687:25)\\ncaused by: Error: db.internal_error/IO error: No such file or directory: while open a file for lock: .rocks/rocks.hub._default/trieDb/LOCK: No such file or directory\\n    at rsDbDestroy (file:///home/node/app/apps/hubble/src/rustfunctions.ts:128:24)\\n    at Hub.attemptCatchupSyncWithSnapshot (file:///home/node/app/apps/hubble/src/hubble.ts:887:7)\\n    at Hub.start (file:///home/node/app/apps/hubble/src/hubble.ts:582:27)\\n    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:687:25)\

Failed to start hub

my guess is that rocksDB fails to install (I looked for the file / folder mentioned and it's missing), but I'm not sure how to solve this. Any ideas?

**Comment by d10r** [comment]
I get the same on bare metal

**Comment by sds** [comment]
Sorry for the delay in response. If you're still seeing this after upgrading to Hubble 1.12.2, and are using an instance with 30+GB of RAM and 200+GB of storage, let us know. Thank you!
