### ISSUE TITLE
bug(hubble): userNameProofsByFid does not return fnames assigned to an fid

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1972]
**What is the bug?**
examples
1. https://nemes.farcaster.xyz:2281/v1/userNameProofByName?name=maya
https://nemes.farcaster.xyz:2281/v1/userNameProofsByFid?fid=121

2. https://nemes.farcaster.xyz:2281/v1/userNameProofsByFid?fid=120 and https://nemes.farcaster.xyz:2281/v1/userNameProofByName?name=nate

**How can it be reproduced? (optional)**

**Comment by adityapk00** [comment]
https://github.com/farcasterxyz/hub-monorepo/pull/1979

**Comment by adityapk00** [comment]
This is now fixed in 1.12.1
