### ISSUE TITLE
[HELP]: ContractFunctionExecutionError: The contract function "register" reverted with the following signature: 0xf90230a9

### ISSUE THREAD

**Issue by AndonMitev** [farcasterxyz/hub-monorepo#1978]
So i'm trying to register user calling bundler contract but then hitting this error:

```
ContractFunctionExecutionError: The contract function "register" reverted with the following signature:
0xf90230a9

Unable to decode signature "0xf90230a9" as it was not found on the provided ABI.
Make sure you are using the correct ABI and that the error exists on it.
You can look up the decoded signature here: https://openchain.xyz/signatures?query=0xf90230a9.
```

Not sure what might be wrong, i'm using:
`BUNDLER_ADDRESS` and `bundlerAbi` from `'@farcaster/hub-web'` and have checked them on optiscan as well but not sure.

This is my code: https://pastebin.com/Ti38wUt9

Pretty straight forward:
1. Generate FID ( using hardcoded one )
2. Get register signature using EOA
3. Get metadata signature usgin APP Account
4. Get signerSignature using EOA
5. Simulate call for register on bundler - fails with error mentioned above

P.S. Sometimes i can see 

```
ContractFunctionExecutionError: The contract function "register" reverted.

Error: InvalidSignature()
``` 

Is like if user do not touch anything for few minutes start throwing from err#1 ( unable to decode signature ) to err#2 ( Invalid Signature ) not sure if both are the same thing tho

**Comment by sds** [comment]
Hey, it's hard to know what exactly is going wrong. Have you tried walking through [our documentation](https://docs.farcaster.xyz/developers/guides/accounts/create-account#create-an-account)?

It's very easy to create an incorrect signature.
