### ISSUE TITLE
bug: Warpcast followers count is defferent with Hub follow count ?

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [farcasterxyz/hub-monorepo#1988]
**What is the bug?**
When i got followers from "/v1/linksByTargetFid?target_fid= 313402",Information returned by it was Inconsistent with wrapcast followers(hub's count is 17,but wrapcast's count is 16).
Apart from inconsistent numbers, the  followers are also inconsistent(There are several Fids inconsistencies, such as 314423 is not follower in warpcast. Besides, Fid like 310164 is follower in warpcast,but not in hub's api ).

How do I need to synchronize consistent information?

**Comment by sanjayprabhu** [comment]
The follower inconsistencies might be related to https://github.com/farcasterxyz/hub-monorepo/pull/1994, which has allowed duplicate and conflicting follows to be merged into the hub. Once the fix is out and the data is corrected, you shuold not be seeing the inconsistencies anymore.

**Comment by sds** [comment]
#1994 was released in Hubble 1.12.2. Please open a new issue if you're still seeing issues (though bear in mind the issue might be purely on the Warpcast side, not Hubble).
