### ISSUE TITLE
sync farcaster data error

### ISSUE THREAD

**Issue by xmenycg** [farcasterxyz/hub-monorepo#1997]
**what is the problem**
sync data is always err, and it seems no peer is connected

<img width="1277" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/6951033/4863281f-b93d-41d9-801f-731a2562eb9b">

<img width="427" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/6951033/71dd65d3-0821-409e-aff4-1c74e9a74df2">

**Comment by xmenycg** [comment]
Ubuntu, and i add "BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282" at .env

**Comment by sds** [comment]
You won't see any data until the initial snapshot has synced. The progress bar in your screenshot shows it was 24% complete. You'll need to wait until it's 100% complete before the Hub's database is initialized, and then it can communicate with the network.

**Comment by sds** [comment]
Also: the reason that's shown as `err` is because the message is sent to stderr so that it doesn't mix with regular output.
