### ISSUE TITLE
Replicator migrate fails on existing database

### ISSUE THREAD

**Issue by donaldinho** [farcasterxyz/hub-monorepo#2000]
**What is the bug?**
Run into a number of issues while running the farcaster replicator migrate command on an existing database.
-  kysely_migration and kysely_migration_lock tables do not get created so migration fails. It's not clear whether this is because the database has existing tables in it or more specifically because there are kysely migration tables in a different schema in the database for another application
- After creating these tables manually the migration fails because we have a table called reactions in another schema
-  Connected with this i could not see a way to put replicator tables in their own schema so had to move other tables out of the public schema to keep things seperated

**How can it be reproduced? (optional)**
Run migrate on a db with existing tables. We're running ponder (ponder.sh) which also has kysely migrations in the ponder schema in our db.

**Comment by sds** [comment]
We recommend you use the [Shuttle project](https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/shuttle) instead of the old replicator. There were many issues with the replicator that won't be fixed.
