### ISSUE TITLE
bug(hubble): Fetch fname transfers when merge fails due to "username not registered"

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#2001]
**What is the bug?**
Hubble only polls the fname server for new names every 5 seconds. This means, if a user registers an fid and an fid and submits UserDataAdd messages within 5 seconds, the username message will be rejected since the hub has not picked it up yet.

We should detect this failure, and check the transfer history for that fid and retry the message automatically. We should also put in some protections so this cannot be used to ddos the fname server (simple check like only x calls/min to the fname server should do, user registration is not high traffic)

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by henryphaver** [comment]
Good finding @sanjayprabhu – We are also getting multiple reports on this from both developers and users. – Because of this issue no username is shown, but instead !123456 which renders the UX useless in almost all cases. Hope this gets prioritized.

**Comment by 0xAegir** [comment]
+1 This is biting us as well.

**Comment by sanjayprabhu** [comment]
Are these fnames eventually fixed or are they still missing? Could you provide some examples? Trying to determine if this is related to the issue above or a separate issue. The above issue happens only for new registrations and should be fixed within a few minutes.

**Comment by andrewhong5297** [comment]
+10 this is making the query experience on Dune a bit buggy, a few users have brought this up

**Comment by henryphaver** [comment]
@sanjayprabhu Actually now 2/3 fixed already by themselves. - Will check if the third one is pending refresh on test system. - If not then been stuck for longer. Will report back.
