### ISSUE TITLE
Replicator syncing data very slowly

### ISSUE THREAD

**Issue by flyingrabbit-lab** [farcasterxyz/hub-monorepo#2017]
Hello. I am trying to run our own  Hub and replicator on Google Cloud. My end goal is to sync Farcaster data into our Postgres database hosted also on Google.

Db configuration is 96 vCPU, 768 Memory.

Hubble is running on a VM with 80 vCPU. Syncing the Hub was pretty quick, 15-20 mins.
The replicator is running on the same VM, connected to our hub, concurrency set to 800.

My issue is that even though the machines seem to be using maximum 80% of their resources syncing into postgres is still super slow.
I am not receiving any errors, the logs say that backfilling the data should take approx 2 hours, but it is showing this since 10 hours. 
<img width="917" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/109557696/85f1219d-496c-468f-9bec-1f7b39fd015c">

I have also added some extra indexes to the db to improve select queries used by the replicator.

Is it possible to further speed up the syncing process, or due to the size of the data this is the best there is?

Thanks for the help!

**Comment by randombishop** [comment]
+1
I am trying to replicate to Postgres too but on a much smaller hardware, it's been running for 5 days already and only got halfway so far. My guess is there are lots of index in the database that slow down the inserts.

**Comment by flyingrabbit-lab** [comment]
@randombishop How much data do you have already in PG? For us replicator synced more than 450 GB, which seems odd to me as our hub uses only 130 GB.

**Comment by sanjayprabhu** [comment]
Hmm, 800 is a very high degree of concurrency, possible it's causing db contention. Could you try lowering it? Also how does db health look like? Are you seeing any deadlocks or timeouts?

**Comment by flyingrabbit-lab** [comment]
Cloud sql allowed 1K connections, cpu usage was under 60% (with 96 vCPU).
Deadlocks only appeared for a 3 minute period for the past week since I am trying to replicate the data.
Lowering concurrency only increases backfill time.

I have seen a few of these Info messages after starting the replicator, but no errors.
Job 73816705 took too long and has stalled.

**Comment by flyingrabbit-lab** [comment]
@randombishop Have you managed to sync the data into PG?

**Comment by randombishop** [comment]
@flyingrabbit-lab Not yet, progress seems to be 80%:
`Backfilled events for 479559 of 595301 FIDs. Estimated time remaining: 1 week, 2 days, 7 hours, 19 minutes, 14 seconds`

**Comment by sds** [comment]
Hey all, we've officially deprecated the Replicator due to issues such as this one. We recommend you have a look at the [Shuttle package](https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/shuttle) if you want to build a service that ingests messages from hubs into another data source. Thanks!
