### ISSUE TITLE
bug(hubble) Missing userdata

### ISSUE THREAD

**Issue by saez0pub** [farcasterxyz/hub-monorepo#2021]
**What is the bug?**
I'm missing a user data of type [USER_DATA_TYPE_USERNAME : 6](https://www.thehubble.xyz/docs/httpapi/userdata.html) on my hubble
It is also mising on hoyt but not on lamia

**How can it be reproduced? (optional)**
Problematic hub:
```
yarn console -s hoyt.farcaster.xyz:2283
yarn run v1.22.19
$ node build/cli.js console -s hoyt.farcaster.xyz:2283
(node:21222) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
hoyt.farcaster.xyz:2283 hub>
Welcome to the Hub console. Type '.help' for a list of commands.
Connecting to hub at "hoyt.farcaster.xyz:2283"
Connected Info: {"version":"1.12.1","isSyncing":true,"nickname":"hoyt","rootHash":"029d30612a5dd043ca3d5003624592b899a9ea00","dbStats":{"numMessages":387653827,"numFidEvents":615757,"numFnameEvents":430449,"approxSize":140674946595},"peerId":"12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo","hubOperatorFid":9152}
hoyt.farcaster.xyz:2283 hub> (await rpcClient.getUserDataByFid({fid: 547628})).value.messages.map((r) => r.data.userDataBody).filter((data) => data.type === 6)
[]
hoyt.farcaster.xyz:2283 hub>
✨  Done in 6.97s.
```
Good hub: 
```
yarn console -s lamia.farcaster.xyz:2283
yarn run v1.22.19
$ node build/cli.js console -s lamia.farcaster.xyz:2283
(node:21250) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
lamia.farcaster.xyz:2283 hub>
Welcome to the Hub console. Type '.help' for a list of commands.
Connecting to hub at "lamia.farcaster.xyz:2283"
Connected Info: {"version":"1.12.1","isSyncing":false,"nickname":"lamia","rootHash":"93c8cfee2d7017d4b2896a4f7b9b8a116fa350e1","dbStats":{"numMessages":389216729,"numFidEvents":615758,"numFnameEvents":430449,"approxSize":138098604674},"peerId":"12D3KooWJECuSHn5edaorpufE9ceAoqR5zcAuD4ThoyDzVaz77GV","hubOperatorFid":9152}
lamia.farcaster.xyz:2283 hub> (await rpcClient.getUserDataByFid({fid: 547628})).value.messages.map((r) => r.data.userDataBody).filter((data) => data.type === 6)
[ { type: 6, value: 'doctorv' } ]
lamia.farcaster.xyz:2283 hub>
```

**Additional context (optional)**
Does this can explain why I'm missing data ?
Do I have to resync my hub 🙀 ?

**Comment by saez0pub** [comment]
Here are another exemples with the good hubble and the bad hubble not always the same.
All are missing on my hubble, sometimes on lamia, sometimes on hoyt, sometimes on neynar.

lamia:
```
lamia.farcaster.xyz:2283 hub> problematicFids=[547628,618466,619800]
[ 547628, 618466, 619800 ]
lamia.farcaster.xyz:2283 hub> for (const fid of problematicFids) { console.log(fid,(await rpcClient.getUserDataByFid({fid})).value.messages.map((r) => r.data.userDataBody).filter((data) => data.type === 6))}
547628 [ { type: 6, value: 'doctorv' } ]
618466 [ { type: 6, value: 'kuku23' } ]
619800 []
```
hoyt:
```
hoyt.farcaster.xyz:2283 hub> problematicFids=[547628,618466,619800]
[ 547628, 618466, 619800 ]
hoyt.farcaster.xyz:2283 hub> for (const fid of problematicFids) { console.log(fid,(await rpcClient.getUserDataByFid({fid})).value.messages.map((r) => r.data.userDataBody).filter((data) => data.type === 6))}
547628 []
618466 []
619800 [ { type: 6, value: 'balaji2003' } ]
```

neynar:
```
bootstrap.neynar.com:2283 hub> problematicFids=[547628,618466,619800]
[ 547628, 618466, 619800 ]
bootstrap.neynar.com:2283 hub> for (const fid of problematicFids) { console.log(fid,(await rpcClient.getUserDataByFid({fid})).value.messages.map((r) => r.data.userDataBody).filter((data) => data.type === 6))}
547628 [ { type: 6, value: 'doctorv' } ]
618466 []
619800 []
```

**Comment by sanjayprabhu** [comment]
Hmm, I think this is likely due to fname transfers not being present at the time of merge and the message being rejected. Diff Sync should be be catching and fixing these, not sure why it didn't let me investigate.

I think https://github.com/farcasterxyz/hub-monorepo/pull/2013 should reduce the occurrences of these

**Comment by saez0pub** [comment]
Hello,

My hubble and lamia seems to have gather the missing data for these 3 FID.
I'm checking if I'm still missing user data in my hubble.
Is there a way to ask for refresh the user data or it's automatic ?

Thanks.

**Comment by saez0pub** [comment]
It seems I'm missing ~ 187K usernames in my hubble.
I've randomly picked 100 fid without username in my hubble instance:
```
892,28230,30185,30653,30752,31688,37075,40182,40860,41433,41812,41910,42624,44774,45290,45850,46448,47571,49269,49889,53295,53316,54343,54417,57723,57838,67164,67972,68157,69949,72880,77664,77722,81586,85547,85763,85893,86808,87498,96416,97199,97305,102769,105551,108166,108543,110014,111431,111656,112133,112481,112530,114166,114515,117286,118803,120646,121863,122338,123407,124913,125965,126839,127954,128226,130965,131359,137509,142443,144318,145830,150570,150800,158004,158427,160011,161827,163112,165232,167682,174946,176516,177119,180732,183821,183845,183898,189079,202110,211362,242852,244913,288867,293237,338588,362110,364728,392514,597017,641569
```
for each:
* Not found on lamia, hoyt, neynar and my hubble.

If I look at the fid 892: Maybe the message had never been sent.
* Not found on lamia, hoyt, neynar and my hubble.
* Is in the fname registry: https://fnames.farcaster.xyz/transfers?fid=892 (last transfert is 0x0x0x0x0)
* Still on fid 892: https://fnames.farcaster.xyz/transfers?name=0x0x0x0x0
* Has a problem on warpcast: https://warpcast.com/0x0x0x0x0

![Screenshot 2024-06-11 at 10 16 38](https://github.com/farcasterxyz/hub-monorepo/assets/3484146/3013fa3d-4aee-475e-b553-bbff9a4c3704)
Similar problem on 189079 (name [xiaoyuwan8](https://warpcast.com/xiaoyuwan8))

the 98 other fids: not found in the registry and the 4 hubble instances.

Is this expected ?

**Comment by sanjayprabhu** [comment]
Looking at some of the fids, it looks like the messages to update the user name were never published, we don't have a record of them in our db either. So, this is expected. Especially if warpcast also shows only the <!fid>.  If warpcast shows an actual username, and the hub does not have it, then it's possible we missed publishing that message. If you find any instances of this, let us know.

The fname registry just records who is authorized to use the fname, they still need to publish the message to the hub to set it.

**Comment by saez0pub** [comment]
Ok, I won't check the 187K missing username, I will assume it is a missing message.
Thank you for your help.
