### ISSUE TITLE
No payment method accepted for Android users in Brazil.

### ISSUE THREAD

**Issue by TermelCarjun** [farcasterxyz/hub-monorepo#2023]
**What is the bug?**
A concise, high level description of the bug and how it affects you
"According to the reviews of the Warpcast app on the Brazilian Android Play Store, all payment methods fail when trying to create and access the account. This bug has persisted for over six months. There is no feedback from the developers, not even my international prepaid debit card from Crypto.com was accepted. The Play Store support claims that it is a bug in your app. Thousands of Brazilians wish to have an account on the site because Twitter confuses the marketing we do for web3 projects as bots. I myself have my X account suspended for this reason. Please, solve this bug. Thank you"
Tercio Carvalho

**Comment by sds** [comment]
Please reach out to Warpcast support. This repository is separate/unrelated to Warpcast. Thanks.
