### ISSUE TITLE
bug(core) Faker library is bundled instead of being set as dependency

### ISSUE THREAD

**Issue by porenes** [farcasterxyz/hub-monorepo#2031]
**What is the bug?**
The issue has been introduced by https://github.com/farcasterxyz/hub-monorepo/pull/961
Instead of removing the import of Faker lib, removing it from the package.json dependency when it is actually used by farcaster/core made things worse as now the entire faker lib is bundled with farcaster/core.
As a consequence, it will be imported multiple times if other modules use it, and it generates a SWC error in NextJs build (at least), as it creates a conflict of identifier.
As a consequence, projects using farcaster/core have to disable SwcMinify for NextJs compilation. This is a bad practice and will not be possible anymore with NextJs15.

You can see an example on the opensource project Herocast (cc @hellno )
https://github.com/hero-org/herocast/blob/fb5d35350aa1214e915d4f0fa0c6ed7ba1f36fea/next.config.mjs#L4

Here is a Farcaster conversation on the topic :
https://warpcast.com/patxol.eth/0x00a51f22

**How can it be reproduced? (optional)**
You can try to build Herocast without `swcMinify:false`
You will get the follosing error :
![image](https://github.com/farcasterxyz/hub-monorepo/assets/2078661/fd47ac2a-7e24-4a12-a511-45d5b9817b2c)

**Additional context (optional)**
We are able to reproduce it on the F4R codebase as well.
It might be interresting to consider extracting from 'core' any usage of Faker, but as a first step re-introducing it as a normal module dependency should fix compiler issues.

**Comment by hellno** [comment]
ran into this with https://github.com/hero-org/herocast and only way to fix that reliably worked was to turn of swc minify. Would love to get a more stable solution for this

**Comment by michalkvasnicak** [comment]
Faker is bundled because of this line https://github.com/farcasterxyz/hub-monorepo/blob/32ba027b080286a70b7ad8b71875493aa7b0440f/packages/core/src/factories.ts#L1
