### ISSUE TITLE
Log-In Issue

### ISSUE THREAD

**Issue by vivaldi888** [farcasterxyz/hub-monorepo#2035]
Hi there,
I recently claimed farcaster ID "0x336c" via Phaver app. When I login with my custodial signer recovery phrase(used same to claimed farcaster account), the app. throws an error:
{
  "error": "\n######################################################################\n\nHandledFetchError\n...message: getOnboardingState 403 - No active Warpcast signer exists for FID undefined\n...name: Farcaster API Error\n...absoluteUrl: [https://client.warpcast.com/v2/onboarding-state\n...body](https://client.warpcast.com/v2/onboarding-state%5Cn...body): undefined\n...endpointName: getOnboardingState\n...hasTimedOut: false\n...isNetworkError: false\n...method: GET\n...relativeUrl: /v2/onboarding-state\n...resolvedTimeout: 20000\n...response: [object Object]\n...responseData: [object Object]\n...status: 403\n...timeout: undefined\n\n######################################################################\n",
  "localTimestamp": 1717866980139,
  "unauthed": true
}

My FID is: 641394

Anybody Help.

**Comment by sds** [comment]
Hey @vivaldi888, this is the Farcaster project, not Warpcast. Please use Warpcast's support—thank you!
