### ISSUE TITLE
bug (hubble):No peers or incoming gossip connections

### ISSUE THREAD

**Issue by easyX1X** [farcasterxyz/hub-monorepo#2041]
**What is the bug?**
No peers or incoming gossip connections

**How can it be reproduced? (optional)**
So far no solution has been found for this problem

**Additional context (optional)**
The methods specified in the repository are not suitable for solving the problem

**Comment by 0ndrec** [comment]
same

![Screenshot 2024-06-12 at 12-49-30 Hubble Dashboard - Dashboards - Grafana](https://github.com/farcasterxyz/hub-monorepo/assets/30905073/935193ae-f111-47ae-ac69-9260520c0831)

**Comment by Mirado97** [comment]
When are you going to fix it? Port 2283 is open as it should be.
![1](https://github.com/farcasterxyz/hub-monorepo/assets/100938207/a61565b3-16f4-4232-bea6-a5887b95c380)
![2](https://github.com/farcasterxyz/hub-monorepo/assets/100938207/18f7e97d-5fd1-41ea-ab37-c1cf27eb7b4c)

**Comment by Zikett** [comment]
same

**Comment by 8-vaka-8** [comment]
have u tried solution that provided in the official doc ? https://docs.farcaster.xyz/hubble/troubleshooting#no-peers-or-incoming-gossip-connections

**Comment by Mirado97** [comment]
> Вы пробовали решение, представленное в официальном документе? https://docs.farcaster.xyz/hubble/troubleshooting#no-peers-or-incoming-gossip-connections

Yes, I did. It was useless.

**Comment by sefdaser** [comment]
I confirm all of the above. There is definitely a bug somewhere. On our channel more than 20 people show screenshots with this error. And I also saw such screenshots on the resources

**Comment by guilosshamal** [comment]
I also support this error message. We have people in Discord who have installed this node. All have shown similar screenshots. When will this be fixed?

**Comment by guilosshamal** [comment]
> Вы пробовали решение, представленное в официальном документе? https://docs.farcaster.xyz/hubble/troubleshooting#no-peers-or-incoming-gossip-connections

Can you show how your .env fixed by this method looks like?

**Comment by easyX1X** [comment]
Yes, sure. but unfortunately this did not change the situation (

**Comment by 8-vaka-8** [comment]
> Can you show how your .env fixed by this method looks like?
Yep.
```
> head -3 ./hubble/.env
FC_NETWORK_ID=1
#BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282
BOOTSTRAP_NODE=/dns/nemes.farcaster.xyz/tcp/2282
```

manually added options BOOTSTRAP_NODE (uncommented one provided here https://docs.farcaster.xyz/hubble/networks#mainnet)

BTW from time to time i have the same inscriptions. As well, i didn`t find any description of how it must work, so...

**Comment by Mirado97** [comment]
> > Можете ли вы показать, как выглядит ваш .env, исправленный этим методом?
> 
> Ага
> 
> ```
> > head -3 ./hubble/.env
> FC_NETWORK_ID=1
> #BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282
> BOOTSTRAP_NODE=/dns/nemes.farcaster.xyz/tcp/2282
> ```
> 
> добавленные вручную параметры BOOTSTRAP_NODE (без комментариев здесь https://docs.farcaster.xyz/hubble/networks#mainnet )
> 
> Кстати, время от времени у меня появляются одни и те же надписи. Да и описания того, как это должно работать, я не нашел, так что...

Yeah, I have the same .env

**Comment by 8-vaka-8** [comment]
I assume it relates to your node score within network. Pay attention to the defenitions of "Inbound Gossip Connections" and "Inbound Sync Attempts" on grafana page. So, everyone have it's own score and i suppose the more uptime and stability the more points you will have. kinda karma xD

**Comment by Mirado97** [comment]
> Я предполагаю, что это связано с оценкой вашего узла в сети. Обратите внимание на определения «Входящие сплетни» и «Входящие попытки синхронизации» на странице графаны. Итак, у каждого свой балл, и я полагаю, чем больше времени безотказной работы и стабильности, тем больше очков вы получите. какая-то карма xD

![3](https://github.com/farcasterxyz/hub-monorepo/assets/100938207/b2748d06-c47e-4caf-8bfb-7fea0e686321)
 Here's mine, for instance. It's beautiful everywhere. But this Synchronization is working or broken, I don't know. It shows a port. It's open and it's working

**Comment by 8-vaka-8** [comment]
how much your uptime for now? try to check graphs for 24 hours for example. inc i have some inbound sync attempts

**Comment by myasobicha** [comment]
> ![image](https://private-user-images.githubusercontent.com/123086974/339255964-8dd1ce5c-25c5-46e5-9467-5d449501a313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDA1NzAsIm5iZiI6MTcxODMwMDI3MCwicGF0aCI6Ii8xMjMwODY5NzQvMzM5MjU1OTY0LThkZDFjZTVjLTI1YzUtNDZlNS05NDY3LTVkNDQ5NTAxYTMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNzM3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDUwNmNhMmRlN2UyNGZmOTk5OTlkOTlkZjJiNzM3MThlNzVkMTliMzA5NzFhYTg1NWQwNTk0YmExYjg4ZGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lACQE89RSIfghlknxVk-zIX_ChJRs-q0afiZI4ZYq4A)
> 
> I sometimes get such errors, I think this is also related to the ports somehow

same problem, ports are open

**Comment by sds** [comment]
Hey all, this looks similar to [this issue](https://github.com/farcasterxyz/hub-monorepo/issues/2061#issuecomment-2174017924). Hubs need to have a public IP address that is reachable. If you're running a hub in your home network, you're probably behind a NAT, which means it isn't reachable.

**Comment by huzal266** [comment]
> When are you going to fix it? Port 2283 is open as it should be. ![1](https://private-user-images.githubusercontent.com/100938207/338947804-a61565b3-16f4-4232-bea6-a5887b95c380.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODgzMDMsIm5iZiI6MTcyNDU4ODAwMywicGF0aCI6Ii8xMDA5MzgyMDcvMzM4OTQ3ODA0LWE2MTU2NWIzLTE2ZjQtNDIzMi1iZWE2LWE1ODg3Yjk1YzM4MC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxMjEzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzYzYjhhZTVkMWZhMzc1MTMyMDNkYTYxOTUxODQ0ZWYxMWZhODgwOWI4MTMwNDdmZDNjM2RkMDM2MDUzZmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L1RezuaxJWIMIFRWJdPxOzmpHzsdj0E7n0VEpbtwTOY) ![2](https://private-user-images.githubusercontent.com/100938207/338947940-18f7e97d-5fd1-41ea-ab37-c1cf27eb7b4c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODgzMDMsIm5iZiI6MTcyNDU4ODAwMywicGF0aCI6Ii8xMDA5MzgyMDcvMzM4OTQ3OTQwLTE4ZjdlOTdkLTVmZDEtNDFlYS1hYjM3LWMxY2YyN2ViN2I0Yy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxMjEzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjQyMDNjYzY1ZmM4YzM4ODVjZDNhYTc4NTdmOTkxZjhiMTBhZWYyY2U0ZGIyYzA0ODRiMDZkMTRmMGE2NDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ddxbz6iN559rL-JnovDdB8JKojQBMHxxr5RXPwFgNZY)

How can I set port number in Contabo?
