### ISSUE TITLE
farcasterxyz / hub-monorepo

### ISSUE THREAD

**Issue by Mirado97** [farcasterxyz/hub-monorepo#2057]
The error is that this hub does not respond adequately to open port 2283. In other words, the hub simply does not see the open port, and only a red label is displayed on the screen (on the screenshot). The necessary recommendations from the official manual (like adding the BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282 parameter to .env) were also implemented. It turned out to be useless.
I'm waiting for an official response from the developers.
![4](https://github.com/farcasterxyz/hub-monorepo/assets/100938207/a3df35cd-2936-4d9c-8da0-d3db704d6899)
![5](https://github.com/farcasterxyz/hub-monorepo/assets/100938207/d17f5de0-7872-42b6-9093-eef965b046e6)

**Comment by sds** [comment]
Hey @Mirado97, if I'm understanding your question correctly, I believe the answer can be found [here](https://github.com/farcasterxyz/hub-monorepo/issues/2061#issuecomment-2174017924). Thanks!
