### ISSUE TITLE
Hubble HTTP endpoint returning db error

### ISSUE THREAD

**Issue by gskril** [farcasterxyz/hub-monorepo#2067]
**What is the bug?**
Hubble's `castByParent` HTTP endpoint returns an error with certain `url` params.

**How can it be reproduced?**
`GET https://hoyt.farcaster.xyz:2281/v1/castsByParent?url=https://warpcast.com/~/channel/page`

See the response

```
{
  "code": 2,
  "details": "db.internal_error/could not get message with key: [1, 129, 11, 134, 0, 1, 111, 110, 101, 6, 78, 209, 172, 203, 162, 11, 104, 228, 239, 164, 151, 212, 243, 3, 81, 109, 55, 199, 100, 32]",
  "metadata": {
    "errcode": [
      null
    ]
  }
}

```

**Comment by Wazzymandias** [comment]
Thank you for the report. I didn't realize issues auto-resolve when PR gets merged in. This should be fixed in the next release, or if you pull and run from main branch. Feel free to re-open if the issue persists.
