### ISSUE TITLE
The problem with port 2283

### ISSUE THREAD

**Issue by Zikett** [farcasterxyz/hub-monorepo#2072]
**What is the bug?**

I've seen a lot of people posting about the port 2283 problem and read the replies. But they probably have nodes on their home network. 

But I have a problem with port 2283 on VPS server and my friends have the same problem. We rent servers from different companies, but the problem is the same for everyone. Dashboard shows that port 2283 is not open, but it is not, I opened it with iptables, I also tried to open it with UFW. I have also asked the company tech support to open ports on their end, they say they don't block them. I have provided a screenshot of my Dashboard for 24 hours, and in 24 hours only 7.5 Inbound Sync Attempts. I think this is very low or not? How can I solve this problem or is it a problem in node or Dashboard is showing wrong information?

Specifications of my VPS: Ubuntu 22.04 6CPU + 16RAM + 300 Gb SSD + 1 Gbit/s  

**How can it be reproduced? (optional)**
I have provided a screenshot of my Dashboard for 24 hours, and in 24 hours only 7.5 Inbound Sync Attempts
![Снимок экрана 2024-06-19 130705](https://github.com/farcasterxyz/hub-monorepo/assets/123086974/dcad7621-1a9a-4f5f-ba00-e5d3bd357966)

**Comment by Zikett** [comment]
![image](https://github.com/farcasterxyz/hub-monorepo/assets/123086974/3bb7bc08-5698-4340-9b6d-7fd9d76a5022)

**Comment by prav33nm** [comment]
Hi, @Zikett
I am having the same issue. My ports were open, but the problem still persists. Have you fixed it by any chance?

**Comment by Zikett** [comment]
> Hi, @Zikett I am having the same issue. My ports were open, but the problem still persists. Have you fixed it by any chance?

No, I'm waiting for an answer.

**Comment by ABarinovEcom** [comment]
I am having the same issue. My ports were open, but the problem still persists. Have you fixed it by any chance?
![image](https://github.com/farcasterxyz/hub-monorepo/assets/124115884/7afc7654-3f63-4b2e-a716-117c82bdd972)

**Comment by Zikett** [comment]
> I am having the same issue. My ports were open, but the problem still persists. Have you fixed it by any chance? ![image](https://private-user-images.githubusercontent.com/124115884/345884278-7afc7654-3f63-4b2e-a716-117c82bdd972.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjI1NDQsIm5iZiI6MTcyMDM2MjI0NCwicGF0aCI6Ii8xMjQxMTU4ODQvMzQ1ODg0Mjc4LTdhZmM3NjU0LTNmNjMtNGIyZS1hNzE2LTExN2M4MmJkZDk3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNDI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmEzZTliODY1ZjhjMjZkNzViMzZlOGU3ZjI5MmRmYjhlYzg2MGZjZDg3MzJiNzllMGY3MGQ1NTA4Mjg0ZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GHwNH43xIMvAQA-4p_cxgNzReOPn3kqAaZbTIIeNUWA)

no, I'm waiting

**Comment by sds** [comment]
It doesn't make much sense to me that your port would only be open _some_ of the time, unless your hub is down periodically.

Do you hub logs mention anything about the hub terminating/restarting?

What happens when you `curl` your hub's public IP address at port 2283? You can try something like the following:

```bash
⨠ curl https://lamia.farcaster.xyz:2283 -i
HTTP/2 415
```

In this case, the response is expected since we're trying to use HTTP/1.1 for a gRPC endpoint. If you're not seeing that response, however, then the issue is a network configuration problem with your VPS/cloud provider.

**Comment by Zikett** [comment]
> Мне не кажется логичным, что ваш порт может быть открыт только _часть_ времени, если только ваш концентратор периодически не выходит из строя.
> 
> Есть ли в журналах вашего концентратора упоминания о завершении работы/перезапуске концентратора?
> 
> Что происходит, когда вы используете `curl`публичный IP-адрес вашего концентратора на порту 2283? Вы можете попробовать что-то вроде следующего:
> 
> ```shell
> ⨠ curl https://lamia.farcaster.xyz:2283 -i
> HTTP/2 415
> ```
> 
> В этом случае ответ ожидаем, так как мы пытаемся использовать HTTP/1.1 для конечной точки gRPC. Однако, если вы не видите этот ответ, то проблема заключается в сетевой конфигурации вашего провайдера VPS/облака.

My VPS server has been online for a whole month and it has never been turned off, there have been no problems with the Internet either. I periodically watch garfana's dashboard. After entering your command, I received the same response.
![Снимок экрана 2024-07-09 121215](https://github.com/farcasterxyz/hub-monorepo/assets/123086974/e0f4f879-74b0-4688-bdfb-29b06a32a25a)

**Comment by Zikett** [comment]
> It doesn't make much sense to me that your port would only be open _some_ of the time, unless your hub is down periodically.
> 
> Do your hub logs mention anything about the hub terminating/restarting?
> 
> What happens when you `curl` your hub's public IP address at port 2283? You can try something like the following:
> 
> ```shell
> ⨠ curl https://lamia.farcaster.xyz:2283 -i
> HTTP/2 415
> ```
> 
> In this case, the response is expected since we're trying to use HTTP/1.1 for a gRPC endpoint. If you're not seeing that response, however, then the issue is a network configuration problem with your VPS/cloud provider.

My VPS server has been online for a whole month and it has never been turned off, there have been no problems with the Internet either. I periodically watch garfana's dashboard. After entering your command, I received the same response.
![Снимок экрана 2024-07-09 121215](https://github.com/farcasterxyz/hub-monorepo/assets/123086974/f425972e-0baa-4bd8-b744-9befdee3062c)

**Comment by sds** [comment]
According to your screenshot you entered the literal exact same command. You need to swap `https://lamia.farcaster.xyz:2283` with whatever IP address your hub's VPS has, and you need to make sure you're running `curl` from a different computer than the VPS.

**Comment by sds** [comment]
Also, if your hub isn't served using HTTPS, switch the URL to something like: `http://1.2.3.4:2283`

**Comment by Zikett** [comment]
> Also, if your hub isn't served using HTTPS, switch the URL to something like: `http://1.2.3.4:2283` (where `1.2.3.4` is your public IP).

![image](https://github.com/farcasterxyz/hub-monorepo/assets/123086974/3d6603ea-c4d4-47a1-812a-37d8439f8fa3)
I used a different vps to test it out. Here's what came up. But dashboard still says that the port is closed.

**Comment by sds** [comment]
Using the IP address in your screenshot, I was able to confirm that you appear to have the necessary ports open (commands ran on my mac, which has a different version of `nc` than most Linux distros, so the below commands might not work correctly on Linux):

```
> echo | nc 185.103.101.62 2282 && echo 'Port open' || echo 'Port closed'
Port open
```

```
> echo | nc 185.103.101.62 2283 && echo 'Port open' || echo 'Port closed'
Port open
```

This might just be a confusing error message that is safe to ignore. The `No Incoming Connections! Are your ports open?` message you see is what Grafana displays when there are a large number of hubs on the network (>13K at time of writing) which was not something we were expecting. 

With so many hubs, it's possible that you might not be getting inbound connections. If you read the tooltip of that message:

>Gossip works even without inbound connections [...]

So if your hub otherwise appears to be working fine, I would ignore this error. Going to close question as answered, but if there's something we're missing from your description let us know.
