### ISSUE TITLE
bug (hubble):

### ISSUE THREAD

**Issue by FireLoveInIce** [farcasterxyz/hub-monorepo#2083]
**What is the bug?**
can't fetch the data when process is 65% and program keeping retry and restart

<img width="453" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/32660493/2482089b-b901-446e-bb30-cec645b9f97c">

**Comment by prasadchinthala01** [comment]
am also getting same error

**Comment by sds** [comment]
Are you sure you have enough disk space and memory? Do you have graphs of your disk + memory utilization at the time the hub terminates?

**Comment by sds** [comment]
Realized this is the same as #2094. Given the number of comments there, combining this with that issue.
