### ISSUE TITLE
Cannot import 12 word seed phrase

### ISSUE THREAD

**Issue by a-k-amit** [farcasterxyz/hub-monorepo#2084]
**What is the bug?**
I tried importing my 12 word seed phrase at Warpcast from the wallet with a Farcaster profile (I claimed that profile from Phaver.com). But it failed after trying several times, it shows an error as per the screenshot below. Also, the "Try Again" button doesn't work.

![Screenshot_20240623_035629_Warpcast](https://github.com/farcasterxyz/hub-monorepo/assets/123064931/e0c2ecd3-4a53-4943-8134-cd494b07128e)

**Comment by sds** [comment]
Hey, this repository is not directly associated with Warpcast. Please use the support channels offered in the mobile app—thanks!
