### ISSUE TITLE
fix(docs): errors in installation instructions

### ISSUE THREAD

**Issue by vsu727** [farcasterxyz/hub-monorepo#2086]
**What is the bug?**

Due to errors or outdated information in the Farcaster Hub installation guides, the Hub cannot be synchronized due to lack of memory which will prevent it from starting and working correctly. This error is very important because it creates difficulties for new users at the very initial stage of work and familiarization with Farcaster Hub

Memory value is 60 GB in the GCP installation guide and 140 GB is the value in the main installation guide. Farcaster Hub currently takes up about 150 GB.

![1 screenshot](https://github.com/farcasterxyz/hub-monorepo/assets/80642652/6873c326-4950-4761-9f27-aedb29af0f93)
![2 screenshot](https://github.com/farcasterxyz/hub-monorepo/assets/80642652/2f4cb31d-4035-46f8-94ef-015e0a4bd4a8)
![3 screenshot](https://github.com/farcasterxyz/hub-monorepo/assets/80642652/a67cd1de-180b-4d51-87fa-8a094ec3838b)
![4 screenshot](https://github.com/farcasterxyz/hub-monorepo/assets/80642652/4443681e-71a3-4a26-8839-db66e84f4a1a)

**Comment by sds** [comment]
Thanks for the PR in #2087. Closing.
