### ISSUE TITLE
"Hub Operator FID is not set" via docker even already set in .env

### ISSUE THREAD

**Issue by kodaicoder** [farcasterxyz/hub-monorepo#2088]
I has setting .env file like documents has guided but
after running I got warning sign that telling "Hub Operator FID is not set " as per image below

![image](https://github.com/farcasterxyz/hub-monorepo/assets/110652592/1fdf2bf9-6032-4693-bf35-d2fc13ab210d)

but I already set it in .env file as per image below

![image](https://github.com/farcasterxyz/hub-monorepo/assets/110652592/5922bede-7024-40f8-8557-30e920423c6c)

**Comment by Chaoqun-Guo** [comment]
you can have a try like this.
docker compose down hubble, then up it again. 
make sure that docker init the .env and make the $XXX variable active.

**Comment by JayJiangEth** [comment]
same issue, i put .env file in  /home/node/app/apps/hubble

**Comment by wjdfx** [comment]
same here:
```{"message":"✅ | Network is MAINNET(1)\n","timestamp":"2024-06-25T06:20:26.199Z","type":"out","process_id":0,"app_name":"hubble"}
{"message":"✅ | Bootstrapping from 4 peers\n","timestamp":"2024-06-25T06:20:26.201Z","type":"out","process_id":0,"app_name":"hubble"}
{"message":"⚠️  | Hub Operator FID is not set\n","timestamp":"2024-06-25T06:20:26.201Z","type":"out","process_id":0,"app_name":"hubble"}```

I can confirm have been config .env file.

**Comment by Cyncra** [comment]
Currently, it seems that only the custody FID created with warpcast is recognized as valid. As a temporary workaround, we are manually modifying the .env file to make it work. When I inquired about this issue with farquest, they advised me to report it in this repository.

**Comment by hoanmq** [comment]
The same for me. Any solution for that?

**Comment by mgladson** [comment]
getting same error message. defining the FID in docker-compose.yml, doesn't help either.

**Comment by kingo233** [comment]
Same issue. Anyone can help me?

**Comment by thuthuyng0119** [comment]
I got the same issue:
`2024-07-07 12:47:05 {"message":"⚠️  | Hub Operator FID is not set\n","timestamp":"2024-07-07T05:47:05.873Z","type":"out","process_id":0,"app_name":"hubble"}`
please help
