### ISSUE TITLE
bug(hubble): Cannot find modules `@farcaster/hub-nodejs` and `@farcaster/core` during build

### ISSUE THREAD

**Issue by hiroyukikumazawa** [farcasterxyz/hub-monorepo#2097]
**What is the bug?**
Cannot find module '@farcaster/core' or its corresponding type declarations.
Cannot find module '@farcaster/hub-nodejs' or its corresponding type declarations.

**Comment by sds** [comment]
Hey @hiroyukikumazawa, can you provide steps to reproduce? 

When I run the following:

```bash
git clone git@github.com:farcasterxyz/hub-monorepo.git
cd hub-monorepo
yarn install
yarn build
```

...I don't get any such errors. My HEAD commit is d1500c007b0ff0e3914b95f2943cc71f77ae94ff at time of writing.

**Comment by sds** [comment]
Closing due to no response. If you can provide reliable reproduction steps, happy to dig deeper. Thanks.
