### ISSUE TITLE
ADDING TO MAJOR WALLETS 

### ISSUE THREAD

**Issue by iandareen** [farcasterxyz/hub-monorepo#2101]
TRUST WALLET
    --Easy to use many of investor use this wallet for holding token with fast phase swapping less fees.
META MASK
   -- META wallet is a secure and easy connection for any web txs safety for connecting sites too.
OTHER SUGGESTION WALLET:
1. KIWI WALLET
2. BITGET WALLET
3. WEB3 BINANCE WALLET

**Comment by sds** [comment]
What exactly are you asking for? Farcaster is a social app, not a token.

I'm going to close this as irrelevant, but if we've misunderstood the ask, let us know.
