### ISSUE TITLE
bug (hubble): Error

### ISSUE THREAD

**Issue by RendallFlegg01** [farcasterxyz/hub-monorepo#2122]
good afternoon, after installing the node and synchronizing, in my logs, after almost every message, an error appears with the same text which you can see in the screenshot. The graph shows the performance of the node and seems to be in order. Tell me what should I do with this error, what should I do next, thank you
![Screenshot_5](https://github.com/farcasterxyz/hub-monorepo/assets/95886367/62a0c72b-d341-4ac5-8734-18d972017c64)
![Screenshot_6](https://github.com/farcasterxyz/hub-monorepo/assets/95886367/e0f2c789-e779-4f17-ad7f-ae0870d0101e)

**Comment by sds** [comment]
Hey @RendallFlegg01, if you're referring to this error:

> submitMessage error: Remove message earlier than the compact state message will be immediatelyl pruned

...then you can safely ignore this error message. It is expected and does not require any action from you.
