### ISSUE TITLE
No peers or incoming gossip connections

### ISSUE THREAD

**Issue by richkidd11** [farcasterxyz/hub-monorepo#2125]
**What is the bug?**
No peers or incoming gossip connections. Already added "BOOTSTRAP_NODE=/dns/hoyt.farcaster.xyz/tcp/2282" into .env file but the issue still persist

FID : 14463

**Comment by sds** [comment]
Hey @richkidd11, check out [this comment](https://github.com/farcasterxyz/hub-monorepo/issues/2131#issuecomment-2215702505), since it answers an issue that sounds suspiciously similar to yours.
