### ISSUE TITLE
Bug in uploading videos and creating of events on the Apple iphone

### ISSUE THREAD

**Issue by Rufusemmanuel** [farcasterxyz/hub-monorepo#2150]
**What is the bug?**

POSSIBLE EVENT CREATION BUG:
While trying to create events this is the error detected

Error loading page
Domain: NSURLErrorDomain
Error Code: -1004
Description: Could not connect to the server.

This may be attributed to possible causes like server unavailability, network connection, DNS issues but I think this is highly unlikely the case as the frames for bounty and poll activities work clearly on the same device simultaneously so I suggest it should be checked for possible bugs or errors

VIDEO UPLOAD ERROR:

On the new update while trying to upload videos to the timeline it disappears after clicking the video to upload even when it was selected carefully. This is the case for the iPhone as I tried on another device and same reoccurrence was detected. The device been used is the iPhone 14 Pro Max so compatibility is not a problem

Thanks for looking into this and I hope it makes farcaster better.

**Comment by manan19** [comment]
@Rufusemmanuel This seems to be a Warpcast specific bug and not related to the farcaster protocol

**Comment by Rufusemmanuel** [comment]
Alright thank you let me report accordingly

**Comment by sds** [comment]
Closing as this repository is for the Farcaster protocol, not Warpcast. Thanks for your understanding.

**Comment by Rufusemmanuel** [comment]
Understood sir🫡, thank you
