### ISSUE TITLE
Error configuring virtual server for Farcaster Hub using GCP tutorial 

### ISSUE THREAD

**Issue by intls** [farcasterxyz/hub-monorepo#2173]
**What is the bug?**

While following the instructions in the official Farcaster documentation for setting up a Hub on Google Cloud Platform (GCP), I encountered an issue during the execution of the terraform apply command. The error message received was:
Error: Error loading zone 'us-central1-a': googleapi: Error 403: Compute Engine API has not been used in project before or it is disabled. 

![GCP Error](https://github.com/user-attachments/assets/8a037588-e9e6-4fcf-b3e5-6a0b1afd9af4)

**Comment by sds** [comment]
Addressed by #2175.
