### ISSUE TITLE
Failed to connect to L1 Ethereum Node

### ISSUE THREAD

**Issue by 0xSomeHoe** [farcasterxyz/hub-monorepo#2182]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/034d8878-6393-45f1-96ed-d162f28509c8">

**Comment by franklyndang** [comment]
I got the same issue. How to fix it?

**Comment by roryhuynh** [comment]
I got the same issue

**Comment by Chomtana** [comment]
Failed to connect to L2 OP Mainnet node

**Comment by sds** [comment]
Who is your ETH RPC provider? The problem almost certainly lies with them, not Hubble.
