### ISSUE TITLE
Inability to buy Warps

### ISSUE THREAD

**Issue by 1Honey11** [farcasterxyz/hub-monorepo#2200]
I want to buy Warps and I get the error Failed to update email.

Same error in both browser and app. 

![Screenshot 2024-07-19 143205](https://github.com/user-attachments/assets/a51238b7-b39d-4ef2-8fb2-05ecfc7873c9)
![Screenshot 2024-07-19 143453](https://github.com/user-attachments/assets/e7749b68-b61e-416e-9f40-be7ec9f7a8a1)
![Screenshot 2024-07-19 143633](https://github.com/user-attachments/assets/e6c08699-2b78-41c3-9aee-a4f6f10e23d6)
![Screenshot 2024-07-19 143818](https://github.com/user-attachments/assets/be86a49c-b7c9-4278-86cb-855815fbe68d)
![Screenshot 2024-07-19 143913](https://github.com/user-attachments/assets/506920e4-96ea-4a5f-839a-49a34a1881e2)
![Screenshot 2024-07-19 144008](https://github.com/user-attachments/assets/43c2b510-0fdb-4d2f-8739-bee930333876)

**Comment by Rufusemmanuel** [comment]
I think this is a Warpcast issue and not a bug from farcaster

**Comment by 1Honey11** [comment]
So where and to whom should I write?

**Comment by sds** [comment]
Find the support contact info in the Warpcast app (click the gear in the nav menu and go to Support).

**Comment by FulcrumN13** [comment]
> I want to buy Warps and I get the error Failed to update email.
> 
> Same error in both browser and app.
> 
> ![Screenshot 2024-07-19 143205](https://github.com/user-attachments/assets/a51238b7-b39d-4ef2-8fb2-05ecfc7873c9) ![Screenshot 2024-07-19 143453](https://github.com/user-attachments/assets/e7749b68-b61e-416e-9f40-be7ec9f7a8a1) ![Screenshot 2024-07-19 143633](https://github.com/user-attachments/assets/e6c08699-2b78-41c3-9aee-a4f6f10e23d6) ![Screenshot 2024-07-19 143818](https://github.com/user-attachments/assets/be86a49c-b7c9-4278-86cb-855815fbe68d) ![Screenshot 2024-07-19 143913](https://github.com/user-attachments/assets/506920e4-96ea-4a5f-839a-49a34a1881e2) ![Screenshot 2024-07-19 144008](https://github.com/user-attachments/assets/43c2b510-0fdb-4d2f-8739-bee930333876)

Did you solve the problem? 
I have the same problem, can't find a solution anywhere.
