### ISSUE TITLE
Node doesnt install

### ISSUE THREAD

**Issue by dibenkodima** [farcasterxyz/hub-monorepo#2220]
![image](https://github.com/user-attachments/assets/20908e55-b43c-4a30-8b58-8ea71946f03c)

**Comment by Father-Web3** [comment]
Same problem tried to install the node on two different VPSs but the problem is the same for me, too

**Comment by soandwhat** [comment]
I think everyone have the same problem.

**Comment by sds** [comment]
Closing as answered.
