### ISSUE TITLE
Hight memory utilisation when running hubble.

### ISSUE THREAD

**Issue by gauravrautela** [farcasterxyz/hub-monorepo#2221]
**What is the bug?**
Very hight memory utilisation of memory when running hubble node.
<img width="927" alt="Screenshot 2024-07-29 at 7 28 43 AM" src="https://github.com/user-attachments/assets/d59befd6-cb1a-4e89-b548-0821ebeb65cf">

you can see the memory utilisation to be around more than 90 GB. 

**How can it be reproduced? (optional)**
Running hubble node with farcaster ID. 

**Additional context (optional)**

**Comment by sds** [comment]
Your screenshot shows a **virtual** memory utilization of 90GB. This is not actual memory allocated.

The "RES" column is what you are looking for. That shows 5.9GB.

Closing as not an issue.
