### ISSUE TITLE
feat: How do I add a polygon network?

### ISSUE THREAD

**Issue by Skill127** [farcasterxyz/hub-monorepo#2222]
I read the documentation, I didn't see how to add a polygon network. Tell me, is it possible to add a polygon network now?

**Comment by ATella12** [comment]
Here's a step-by-step guide:

1. Log in to your Farcaster account and navigate to the "Networks" tab.
2. Click the "Add Network" button.
3. Select "Polygon" from the list of available networks.
4. Enter the following details:
    - Network Name: Polygon Mainnet (or any other name you prefer)
    - RPC URL: (or any other Polygon RPC URL)
    - Chain ID: 137 (Polygon's chain ID)
    - Currency Symbol: MATIC (Polygon's native currency)
5. Click "Add Network" to save your changes.

Once you've added the Polygon network, you can use it to deploy and manage your smart contracts, as well as interact with decentralized applications (dApps) built on the Polygon blockchain.

**Comment by Skill127** [comment]
No, how to add an RPC for a node

**Comment by sds** [comment]
No, Farcaster hubs do not support Polygon at this time.

**Comment by Skill127** [comment]
Thank you, then we are waiting
