### ISSUE TITLE
Shuttle streaming busy-waits on redis hub message stream

### ISSUE THREAD

**Issue by tybook** [farcasterxyz/hub-monorepo#2227]
**What is the bug?**

Stream process always pegs a CPU core at 100%. Investigation shows `HubEventStreamConsumer` is busy-waiting on the redis stream for hub messages, checking for stale messages up to ~9k times per second (as determined by the `hub.event.stream.claim_stale` statsd count metric). I think this is because a per-iteration `sleep(10)` was removed in latest change to `packages/shuttle/src/shuttle/eventStream.ts` (commit e5760da0d3d3d0cb0fcc01c7492d1c7d60871987).

**How can it be reproduced? (optional)**

Run example-app stream process and watch CPU usage for that process always be 100%. Check the `hub.event.stream.claim_stale` statsd count metric to see how many times per second `processStale()` is being called.

**Additional context (optional)**
N/A

**Comment by sds** [comment]
Thanks for catching. Fix released in Shuttle 0.5.9.
