### ISSUE TITLE
240gb not enough for synchronization 

### ISSUE THREAD

**Issue by encipher88** [farcasterxyz/hub-monorepo#2260]
![Screenshot_595](https://github.com/user-attachments/assets/c9e9d036-c39a-4f9e-89ae-53de6fb21c8b)

**Comment by gpolyansky** [comment]
now its using over 330gb on my mashine. 
Also here taking place a memory leak, started for 2.6GiB after a few hours its 7+GiB.

**Comment by sds** [comment]
Thanks for the report. Updated docs in #2353 based on what we're seeing for disk usage on our hubs.
