### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by huzal266** [farcasterxyz/hub-monorepo#2288]
I am getting errors in the logs. What could be the reason?
![image](https://github.com/user-attachments/assets/ffd9aea7-a137-42c6-9610-15f0dc0a0ae9)

**Comment by SamuelLHuber** [comment]
looks like you're recieving duplicate messages from other hubs

**Comment by sds** [comment]
Closing as answered. Those errors are normal and expected during normal operation.
