### ISSUE TITLE
Hubble can't seem to install

### ISSUE THREAD

**Issue by Dalu26** [farcasterxyz/hub-monorepo#2289]
**What is the bug?**
A concise, high level description of the bug and how it affects you
Hubble can't seem to be fetched after inputting the required RPCs

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 
Try to run Hubble node using the installation script "curl -sSL https://download.thehubble.xyz/bootstrap.sh | bash"

**Additional context (optional)**
<img width="1104" alt="Screenshot 2024-09-03 at 9 27 18 PM" src="https://github.com/user-attachments/assets/b0c9eb83-b3ab-434a-a36b-a880a1475742">

**Comment by sds** [comment]
Sorry for the delay in response. This looks like a network connectivity issue unrelated to Hubble (`Failed to fetch https://raw.githubusercontent.com/...`) and so we're going to close this as not relevant. 

Check your network configuration, or use [Neynar](https://neynar.com/) to run a hub for you.
