### ISSUE TITLE
A severe program error occurred when importing the Takocast wallet into Warpcast.

### ISSUE THREAD

**Issue by NeuNue** [farcasterxyz/hub-monorepo#2300]
**What is the bug?**
When I imported the wallet registered with another Farcaster client (Takocast) into Warpcast, an error message appeared: "We were unable to retrieve the onboarding state." I was unable to return to the normal login screen even after restarting the app or uninstalling and reinstalling it.

**How can it be reproduced? (optional)**

Debug info:
{
  "error": "\n######################################################################\n\nHandledFetchError\n...message: getOnboardingState 403 - No active Warpcast signer exists for FID undefined\n...name: Farcaster API Error\n...absoluteUrl: https://client.warpcast.com/v2/onboarding-state\n...body: undefined\n...endpointName: getOnboardingState\n...hasTimedOut: false\n...isNetworkError: false\n...method: GET\n...relativeUrl: /v2/onboarding-state\n...resolvedTimeout: 20000\n...response: [object Object]\n...responseData: [object Object]\n...status: 403\n...timeout: undefined\n\n######################################################################\n",
  "localTimestamp": 1725960110954,
  "unauthed": true
}

![IMG_3157B9FE82DF-1](https://github.com/user-attachments/assets/a65a7650-424e-415c-afe3-1b80c15295d2)

**Comment by sds** [comment]
This repository is for Farcaster the protocol, not Warpcast (a client implementation on top of the Farcaster protocol).

The Warpcast app has a support link you can utilize if necessary. Thank you.
