### ISSUE TITLE
feat: support NFT URI's as top level items for cast and reactions

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#231]
**What is the feature you would like to implement?**

Casts, reactions (and potentially follows?) should be able to address an NFT or web page. The NFT part is high priority but the schema should be designed such that it can be extended to arbirtrary URLs as well.

**Why is this feature important?**

One of the most requested user features from the clients and something that increases the usefulness of Farcaster conversations. Likely implemented as soon as v2 ships. 

**Will the protocol spec need to be updated??**
Yes, it will need to update 

**How should this feature be built? (optional)**
TBD

**Comment by pfletcherhill** [comment]
Adding the p2 milestone here so I confirm our flatbuffers schema will support this easily

**Comment by pfletcherhill** [comment]
Closing because the change was made for replies and reactions and the remaining work is tracked here: https://github.com/farcasterxyz/hub-monorepo/issues/845
