### ISSUE TITLE
bug (hubble): 100% disk usage during installation

### ISSUE THREAD

**Issue by Suspend85** [farcasterxyz/hub-monorepo#2312]
Hi!
my hardware: 8 CPU, 16 GB RAM, 320 GB Disk
When I install using command `curl -sSL https://download.thehubble.xyz/bootstrap.sh | bash`, the disk fills up to 100%, stops, and never starts the node.
At first it worked on a 240 GB disk, but now it can't even install on 320.

How i can fix this? Thank you.

**Comment by tar1kunanets** [comment]
I used a 200 GB disk a month ago, and it was fine, but now I have the same problem. I'm curious how much memory I should have to install the node.

**Comment by sds** [comment]
Sounds like while the hub is downloading an initial snapshot, it might use extra disk space to during decompression of said snapshot.

For now, I would suggest increasing disk space to 500GB. The network is growing rapidly and you likely won't be able to work with a 320GB disk for long anyway. We'll update our documentation to make this clearer.

Alternatively, strongly suggest not operating your own hub, and working with a provider like [Neynar](https://neynar.com/).

**Comment by Suspend85** [comment]
> Sounds like while the hub is downloading an initial snapshot, it might use extra disk space to during decompression of said snapshot.
> 
> For now, I would suggest increasing disk space to 500GB+. The network is growing rapidly and you likely won't be able to work with a 320GB disk for long anyway. We'll update our documentation to make this clearer.
> 
> Alternatively, strongly suggest not operating your own hub, and working with a provider like [Neynar](https://neynar.com/).

Good afternoon. Thanks for the reply. I'm currently using a 400Gb disk, 75% utilized. 
And I'm using infura service for node. Is this normal? 
And can you tell me where in the documentation I can see these changes?

**Comment by sds** [comment]
> I'm currently using a 400Gb disk, 75% utilized. And I'm using infura service for node. 
> **Is this normal?** 
What are you using to calculate disk usage? When I run `df -h` on our hubs, I see a total of ~215GB used. What else are you running on the system?

> **can you tell me where in the documentation I can see these changes?**
https://www.thehubble.xyz/intro/install.html#requirements

I can't speak to why your machine is using much more disk space. There are endless reasons depending on how you've configured it. I would strongly suggest using a provider like [Neynar](https://neynar.com/) instead of running your own hub.

**Comment by Suspend85** [comment]
> > I'm currently using a 400Gb disk, 75% utilized. And I'm using infura service for node.
> > **Is this normal?**
> 
> What are you using to calculate disk usage? When I run `df -h` on our hubs, I see a total of ~215GB used. What else are you running on the system?
> 
> > **can you tell me where in the documentation I can see these changes?**
> 
> https://www.thehubble.xyz/intro/install.html#requirements
> 
> I can't speak to why your machine is using much more disk space. There are endless reasons depending on how you've configured it. I would strongly suggest using a provider like [Neynar](https://neynar.com/) instead of running your own hub.

Got it, thanks. 
Sending you a screenshot of the server data:
![photo_2024-10-24_17-10-04](https://github.com/user-attachments/assets/da206792-f372-4205-8e69-1cf757a6bd88)
