### ISSUE TITLE
Error submitting message to hub: HubError: read ECONNRESET / Call cancelled

### ISSUE THREAD

**Issue by eucalyptus-viminalis** [farcasterxyz/hub-monorepo#2377]
**What is the bug?**
Nodejs app fails to submit message using the public `nemes.farcaster.xyz:2283` URL using `HubRpcClient` from `@farcaster/hub-nodejs`.

The error messages I'm getting:
- for `makeUserDataAdd`: `Error submitting message to hub: HubError: read ECONNRESET`
- for `makeCastAdd`: `Error submitting message to hub: HubError: Call cancelled` 

**How can it be reproduced? (optional)**
This bug relates to the [write data example](https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/hub-nodejs/examples/write-data) in the `hub-nodejs` package. In my clone I am using the `getInsecureHubRpcClient` method to create the client using the public hub URL `nemes.farcaster.xyz:2283`.

**Additional context (optional)**
- I've checked that the public key of the signer corresponds to the one recorded onchain by the `KeyRegistry` contract.
- My feeling is that it's a problem with using the `getInsecureHubRpcClient` instead of `getSSLHubRpcClient` but I'm not sure if there is a username and password available to use with the public server.
- It seems I'm only getting this error for submitting messages. e.g. I can run the `chron-feed` example without any problem.

**Comment by sds** [comment]
This isn't a bug—sometimes network connections fail. You need to design your application to be resilient to failure.

When such a failure occurs, try writing to another hub instead. Have your code gracefully failover to the other hub.

**Comment by eucalyptus-viminalis** [comment]
Okay so it's got nothing to do with how I was using the APIs? It was just that the nemes hub I waa using was down or something?
