### ISSUE TITLE
Fix typo in docs/developers/frames/getting-started.md

### ISSUE THREAD

**Issue by Rufusfavour** [farcasterxyz/hub-monorepo#2394]
Using "depedencies" as a comment won't affect the execution of the commands themselves. The commands bun install and bun run dev will still work regardless of the typo in the comment. However, for clarity and professionalism, it's best to correct it to "dependencies."

**Comment by sds** [comment]
Happy to merge a PR addressing this. Thanks.

**Comment by Rufusfavour** [comment]
@sds check PR for effective merging https://github.com/farcasterxyz/docs/pull/352#issue-2731338240
