### ISSUE TITLE
download farcaster snapshot metadata - 404

### ISSUE THREAD

**Issue by albend888-p** [farcasterxyz/hub-monorepo#2458]
Failed to start hub: failed to fetch snapshot metadata - Failed to get latest snapshot from https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json [AxiosError: Request failed with status code 404]

**Comment by vrypan** [comment]
I see the same error.

**Comment by ksalab** [comment]
same error

**Comment by CoshBennis** [comment]
same error

**Comment by dimaudi** [comment]
same error for me

**Comment by 80an** [comment]
same error

**Comment by albend888-p** [comment]
Fix it (perhaps temporarily until the situation with the snapshot becomes clearer):
1. cd ~/hubble && ./hubble.sh down
2. nano docker-compose.yml (cd ~/hubble)  ${CATCHUP_SYNC_WITH_SNAPSHOT:-true}  -> ${CATCHUP_SYNC_WITH_SNAPSHOT:-false} 
3.  cd ~/hubble && ./hubble.sh up

**Comment by 80an** [comment]
> Fix it (perhaps temporarily until the situation with the snapshot becomes clearer):
> 
> 1. cd ~/hubble && ./hubble.sh down
> 2. nano docker-compose.yml (cd ~/hubble)  ${CATCHUP_SYNC_WITH_SNAPSHOT:-true}  -> ${CATCHUP_SYNC_WITH_SNAPSHOT:-**false**}
> 3. cd ~/hubble && ./hubble.sh up

Thanks for the tip, I've already done this a little earlier.

**Comment by albend888-p** [comment]
team fixed issue. 
https://download.farcaster.xyz/ works now.

closed
