### ISSUE TITLE
feat: expire fname ownership to stay in sync with Name Registry

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hub-monorepo#349]
Right now we stream Transfer and Renew events from the Name Registry into the hubs, but we don't expire ownership (i.e. fname --> address) relationships when they naturally expire on the contract.

* [ ] Add a scheduled job to check for expiration when we merge new Name Registry events

**Comment by pfletcherhill** [comment]
The first fnames don't expire until fall 2023, so it's okay to hold off on implementing this until mid-2023. That being said, we should confirm that sync is able to handle fname expirations (deleting `NameRegistryEvent` + revoking `UserDataAdd` messages) when we do get around to implementation.

**Comment by varunsrin** [comment]
no longer relevant since we're moving away from the name registry before Oct 22

cc @sanjayprabhu and @horsefacts to be aware of this ticking clock
