### ISSUE TITLE
feat: index merged messages asynchronously

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hub-monorepo#352]
Right now, we write messages to rocksdb and index them in the same transaction. We should explore indexing messages asynchronously using a separate worker.

**Comment by varunsrin** [comment]
@adityapk00 is this still something worth considering for perf reasons?

**Comment by adityapk00** [comment]
I looked into this, and it's not going to result in much perf gain. Plus, we need indexes right away after merge, so we'll run into sync issues if we don't do it right away.
