### ISSUE TITLE
chore: rocksdb performance research

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hub-monorepo#354]
_*Updated May 1*_

RocksDB is our key-value LSM store used for efficiently storing Hub data on disk in a compact and efficient manner. We use [level/rocksdb](https://github.com/Level/rocksdb) to interact with RocksDB from our Typescript code today. 

RocksDB works reasonably well at 1M messages under practical conditions, and 10M messages under ideal, theoretical conditions. However, we want to design a practical suite of tools that gives us confidence that RocksDB works at 10M messages and 100M messages. 

Also, message quantity is a decent proxy for scale, but there are a number of inter-related likes like scheduled jobs, pruning frequency, transaction structuring, compaction etc. A lot of research needs to be done to develop confidence in our system.  

There are a few open-ended questions that require more research:

- What is the actual bytes on disk for each message type, so that we can estimate requirements for 1M DAU?
- What is most likely going to cause RocksDB to start failing if the network grows at current pace?
- Should we move away from level/rocksdb so that we can take advantage of low level features?
- Can storage and performance be optimized further so that sync completes quickly and does not require swap space?

**Comment by pfletcherhill** [comment]
This issue may be addressed by other, more specific ones. However, we've still yet to test rocksdb at any real scale (>10m messages), which makes me nervous. Also, the javascript tooling for rocksdb is next to non-existent, and we don't yet know when/how/if [the package](https://github.com/Level/rocksdb) we're using for interacting with rocksdb will fail. So I'd like to see some resources put towards researching these questions, but I'm not sure what the priority should be.

**Comment by varunsrin** [comment]
@pfletcherhill to take a pass at articulating some concerning edge cases tonight

**Comment by varunsrin** [comment]
ambiguous ticket, closing for now
