### ISSUE TITLE
feat: connect with multiple peers to sync and download different parts of the trie

### ISSUE THREAD

**Issue by adityapk00** [farcasterxyz/hub-monorepo#366]

**Comment by adityapk00** [comment]
Moved to v2.1.0

**Comment by varunsrin** [comment]
@adityapk00 based on recent perf investigations is this worth keeping around or should we close since the improvemnet is very small?

**Comment by adityapk00** [comment]
This is probably not worth doing now, given snapshot sync and perf improvements
