### ISSUE TITLE
feat: Split HubService into StorageService and SyncService

### ISSUE THREAD

**Issue by adityapk00** [farcasterxyz/hub-monorepo#472]
**What is the feature you would like to implement?**
Split the monolithic HubService into StorageService and SyncService

**Why is this feature important?**
Some hubs may not want to implement the full sync, and this will allow just the Storage Service to be implemented. 

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**

**Additional context**

**Comment by dakshas** [comment]
@adityapk00 Can I give this a shot ?

**Comment by varunsrin** [comment]
@adityapk00 is this still relevant?
