### ISSUE TITLE
bug: @farcaster/js doesn't support browser environments

### ISSUE THREAD

**Issue by deodad** [farcasterxyz/hub-monorepo#494]
**What is the bug?**
The `@farcaster/js` ESM distribution doesn't support browser environments.

**How can it be reproduced? (optional)**
In a frontend project that supports ESM (i.e. Vite, Next, Replit), add an import from @farcaster/js:
```
import { Eip712Signer } from '@farcaster/js';
```
An error like `Module not found: Can't resolve 'module'` or `Uncaught TypeError: (0 , import_module.createRequire) is not a function` will occur since the ESM distribution depends on [node:module](https://nodejs.org/api/module.html).
 
https://replit.com/@adaddeo/farcasterjs-demo#src/index.jsx

**Additional context (optional)**
This dependency comes from this [shim](https://github.com/farcasterxyz/hubble/blob/main/packages/protobufs/tsup.config.ts#L10) added in `@farcaster/protobufs`.

**Comment by adaddeo** [comment]
@adityapk00 any context why this [shim](https://github.com/farcasterxyz/hubble/blob/main/packages/protobufs/tsup.config.ts#L10) was needed?

**Comment by adityapk00** [comment]
This was needed as a workaround for an ESBuild issue where grpc-js wasn't building. Some more info about the underlying issue is here: https://github.com/evanw/esbuild/issues/1921

**Comment by adityapk00** [comment]
There's a task here to move the grpc-js part out into it's own package: https://github.com/farcasterxyz/hubble/issues/473
