### ISSUE TITLE
SyncEngine.performSync fetches all messages from peer

### ISSUE THREAD

**Issue by kcchu** [farcasterxyz/hub-monorepo#536]
**What is the bug?**

`SyncEngine.performSync()` fetches all messages from peer even it already has all the messages.

**How can it be reproduced? (optional)**

Test case snippet:

```typescript
 const engine1 = new Engine(testDb, FarcasterNetwork.FARCASTER_NETWORK_TESTNET);
 const syncEngine1 = new SyncEngine(engine1, testDb);
 const engine2 = new Engine(testDb2, FarcasterNetwork.FARCASTER_NETWORK_TESTNET);
 const syncEngine2 = new SyncEngine(engine2, testDb2);

 await engine1.mergeIdRegistryEvent(custodyEvent);
 await engine1.mergeMessage(signerAdd);
 await engine2.mergeIdRegistryEvent(custodyEvent);
 await engine2.mergeMessage(signerAdd);

 const messages = await addMessagesWithTimestamps([30662167, 30662169, 30662172], engine1);
 for (const message of messages) {
   await engine2.mergeMessage(message);
 }

 // Sanity check, they should equal
 expect(await syncEngine1._trie.rootHash()).toEqual(await syncEngine2._trie.rootHash());

 Date.now = () => 1640995200000 + 30662200 * 1000;

 const snapshot2 = (await syncEngine2.getSnapshot())._unsafeUnwrap();
 // Bug 1
 expect((snapshot2.prefix as Buffer).toString('utf8')).toEqual('00306622');

 const rpcClient = new MockRpcClient(engine2, syncEngine2);
 await syncEngine1.performSync(snapshot2.excludedHashes, rpcClient as unknown as HubRpcClient);

 expect(rpcClient.getAllSyncIdsByPrefixCalls.length).toEqual(1);
 // Bug 2
 expect(rpcClient.getAllSyncIdsByPrefixCalls[0].prefix.toString('utf8')).toEqual('');

// Fetch all SyncIds as a result
 expect(rpcClient.getAllMessagesBySyncIdsCalls.length).toEqual(1);
 expect(rpcClient.getAllMessagesBySyncIdsCalls[0].syncIds.length).toEqual(4);
```

Complete test case: https://github.com/kcchu/hub/commit/2f012cb7c9031c19b4bf545dd230b4fca09e0094

This bug requires the fix in https://github.com/farcasterxyz/hubble/pull/535 to be applied.

**Additional context (optional)**

The issue is composed of (at least) 2 bugs in the SyncEngine.

Bug 1:

The prefix returned by MerkleTrie.getSnapshot() could point to an non-existent node. This behavior is demonstrated in one of the existing test cases https://github.com/farcasterxyz/hubble/blob/03113792084e028d2542f30c69d99fc3efa8e7c2/apps/hubble/src/network/sync/merkleTrie.test.ts#L432-L439

The above test case returns a non-existent node `167`. It is unclear whether it is intentional. However, this behavior causes `MerkleTrie.getDivergencePrefix()` to return the non-existent prefix when two tries has the same excluded hashes.

Bug 2:

Bug 1 further causes `performSync` function to misbehave.

`performSync` calls `fetchMissingHashesByPrefix` with `divergencePrefix`:

https://github.com/farcasterxyz/hubble/blob/03113792084e028d2542f30c69d99fc3efa8e7c2/apps/hubble/src/network/sync/syncEngine.ts#L210-L226

`fetchMissingHashesByPrefix` calls RPC function `getSyncMetadataByPrefix`. Since the `divergencePrefix` does not exist, the RPC function returns an empty node (not error).

`fetchMissingHashesByPrefix ` then calls `fetchMissingHashesByNode`:

https://github.com/farcasterxyz/hubble/blob/03113792084e028d2542f30c69d99fc3efa8e7c2/apps/hubble/src/network/sync/syncEngine.ts#L187-L199

`theirNode` is empty, so it falls into the case at line 187 which calls `getAllSyncIdsByPrefix` with an empty prefix (from the empty node).

From here, SyncEngine fetches all messages from the peer.

**Comment by adityapk00** [comment]
Let me think about Bug 2, but at least for Bug 1, I think we should change behaviour so that fetching a non-existing timestamp returns the highest valid node. i.e., 

```
   const snapshot = await trie.getSnapshot(Buffer.from('1677123')); 
   expect(snapshot.prefix).toEqual(Buffer.from('16')); 
```

It should return the "16" node, which is the highest node that is actually available. This satisfies the original reason this was added: When fetching a timestamp that may not have any messages, fetch the closest timestamp that does have messages, so clients can decide whether to sync.

**Comment by adityapk00** [comment]
Here are some things we can maybe do, I'm curious to hear what you think:

1. I think `getSyncMetadataByPrefix` should not accept an empty Prefix (i.e. root node) as a parameter. That's likely to be a bug in any situation, so we should fail that. Same for `getAllSyncIDsByPrefix`
2. I think your idea that `getDivergencePrefix` to take into account the snapshot prefix is a good one. How exactly do you think it should work? 
3. If `getDivergencePrefix` returns a empty node, we should abort the sync and retry later, which will prevent unnecessary message fetching. 

I'm curious to hear your thoughts, too.

**Comment by adityapk00** [comment]
Ok, I fixed some of the prefix issues, but I'm still a bit confused about the core of this bug. 

Let's assume the worst case scenario - That the `divergencePrefix` is the root node (i.e empty node) or a non-existent node, and `fetchMissingHashesByPrefix` gets called with that.

However, as it starts recursing into the trie in `fetchMissingHashesByPrefix` and `fetchMissingHashesByNode`, the sync algorithm will figure out that the hashes at various levels actually match, and won't fetch any messages. (See https://github.com/farcasterxyz/hubble/blob/main/apps/hubble/src/network/sync/syncEngine.ts#L224)

The only thing that can happen is it will fetch `HASHES_PER_FETCH =50` messages if the root node has less than that many messages, which seems fine. 

Even the `getSyncMetadataByPrefix`, which gets the metadatas, it will only fetch one level before it realizes that the child hashes match.

**Comment by adityapk00** [comment]
In any case, I added some more checks in `fetchMissingHashesByPrefix`, so that even if the divergence or node is bad, it won't unnecessarily fetch messages. Also handles the case where pruning removes messages on the other node before ours. 

In https://github.com/farcasterxyz/hubble/pull/540
