### ISSUE TITLE
docs: add docs for all api calls in the repository 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#555]
**What is the feature you would like to implement?**

Add a markdown file that contains all hubble gRPC API calls. 

**Why is this feature important?**

Make it easier for developers to get started with the Hubs. 

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
Ideally try to autogen some of the code and then document it, but write by hand if necessary.

**Comment by vinliao** [comment]
Hi, I'm trying to familiarize myself with the codebase. I figured out writing this documentation is a pretty good way to do it.

Correct me if I'm wrong, but it seems like the gRPC API endpoints are the ones found in `/packages/js/src/utils.ts`?

Here's a sample of the docs:

`async getCast(fid: number, hash: Uint8Array)`
Description: Retrieves a single cast object by it the author's fid and the cast's hash.
Parameters:
- fid: the id of user in the Farcaster network
- hash: the cast hash
Returns: TODO: example response

`async getCastsByFid(fid: number)`
Description: Retrieves an array of cast objects from a specific user
Parameters:
- fid: the id of user in the Farcaster network
Returns: TODO: example response

`async getCastsByParent(parentId: protobufs.CastId)`
Description: Retrieves an array of cast objects that are children of a specified parent cast.
Parameters:
- parentId: The ID of the parent cast. `CastId: { fid: number, hash: Uint8Array }`
Returns: TODO: example response

Still figuring out how to run Hubble locally so I can actually see the what the return values of these functions are. It seems beginner-friendly enough that I can help contribute to this Issue.

**Comment by varunsrin** [comment]
So there are two level of documentation we will need to write: 

1. docs for farcaster/protobufs, which document the raw .proto files and rpc methods (I've started this [here](https://github.com/farcasterxyz/hubble/pull/562))
2. docs for farcaster/js which documents the typescript endpoints (currently not being worked on) 


If you wanted to pick up #2, that would be much appreciated! Some considerations: 

1. Can we auto-generate the docs by adding comments into the code and using some tool to produce files?
2. Make sure that (1) doesn't conflict with auto-generated ts-proto files, since changes will not be preserved in those files
3. Can we generate them as simple markdown files or something that renders in github? 

I would suggest picking a couple of complicated API methods and documenting it thoroughly, so we can discuss style, format etc. Once we have that in place we can expand to do the others.

**Comment by vinliao** [comment]
Got a basic version up with TypeDoc: https://github.com/vinliao/fcjs-docs-md/blob/master/modules.md.

Couple thoughts:
1. It needs to be simpler (here's a function, here's the input params, here's the JSON output, and here's one example). Ex: instead of having `Promise<HubResult<ClientReadableStream<EventResponse>>>` in the return type, just spit out the JSON.
2. The ideal would be having a docs so simple, devs can go from knowing nothing to a "hello world" hub interaction in 5 minutes
3. Do we need to have TypeDoc installed on farcaster/js and a `doc` script on its `package.json`, or is this a one-off thing?

Thoughts?

**Comment by vinliao** [comment]
Here's the improved version. Again, generated with TypeDoc, but with code examples. The "output param explained" is generated with GPT, so it might be whacky, but it can be easily fixed later (I just want to get the formatting right first). Any thoughts on this?

## Methods

### getIdRegistryEvent

Returns information about an IdRegistryEvent for the specified Fid.

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `fid` | `number` | The Fid to look up. |

**`Example`**

```ts
// Example usage:
import { Client } from "@farcaster/js";
const client = new Client(YOUR_RPC_URL);
const unwrap = (data) => console.log(data._unsafeUnwrap());
client.getIdRegistryEvent(9000).then(unwrap);

// Will output:
 {
   _protobuf: // same data as below, but in raw bytes
   blockHash: '0xe86ff7b3452a86aa848e53ba03d3a2d0c678732a2e051d5ac5c1e808daec86fe',
   blockNumber: 8463597,
   fid: 9000,
   transactionHash: '0x2d116c68060036ddfc8d6105703ed78cc63f910180630ec714e700c21bb83544',
   logIndex: 219,
   to: '0x027c02f30df092f886f1af6d364b27bb62c1564d',
   type: 1,
   from: undefined
 }

// Output params explained:
// - blockHash: The hash of the block containing the event.
// - blockNumber: The number of the block containing the event.
// - fid: The Fid of the event.
// - transactionHash: The hash of the transaction containing the event.
// - logIndex: The index of the event in the block.
// - to: The address of the contract that emitted the event.
// - type: The type of the event.
// - from: The address of the sender of the transaction containing the event.
```
___

### getNameRegistryEvent

Returns information about a NameRegistryEvent for the specified username.

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `fname` | `string` | The username to look up. |

**`Example`**

```ts
// Example usage:
import { Client } from "@farcaster/js";
const client = new Client(YOUR_RPC_URL);
const unwrap = (data) => console.log(data._unsafeUnwrap());
client.getNameRegistryEvent("dwr").then(unwrap);

// Will output:
 {
   _protobuf: // same data as below, but in raw bytes
   blockHash: '0x318c1013788674810b4cc15763afa9bbe5a2cd184a6a932a46bd64ba71b55684',
   blockNumber: 7648814,
   fname: 'dwr',
   transactionHash: '0x975f9e1c3cd38406df8e2c2458be8236d512d9784323bfbff077d2061e88f147',
   logIndex: 87,
   to: '0x74232bf61e994655592747e20bdf6fa9b9476f79',
   type: 1,
   from: '0x0000000000000000000000000000000000000000',
   expiry: 1695524928000
 }

// Output params explained:
// - blockNumber: The block number in which the NameRegistryEvent was emitted.
// - blockHash: The block hash in which the NameRegistryEvent was emitted.
// - transactionHash: The transaction hash in which the NameRegistryEvent was emitted.
// - logIndex: The log index in which the NameRegistryEvent was emitted.
// - fname: The username.
// - from: The address from which the username was transferred.
// - to: The address to which the username was transferred.
// - type: The type of the NameRegistryEvent. 1 for a transfer, 2 for an expiry.
// - expiry: The expiry timestamp of the username.
```

**Comment by varunsrin** [comment]
this is great, i love it!

**Comment by varunsrin** [comment]
protobuf docs are completed: https://github.com/farcasterxyz/hubble/pull/562

@vinliao will pick up the docs for the ts interfaces

**Comment by vinliao** [comment]
I'll make a PR soon and we can continue there. Small note: currently watching #585 (hopefully seeded with actual data) so I can try out all the functions in the JS packages.

**Comment by varunsrin** [comment]
closing since we took a different approach to documentation
