### ISSUE TITLE
feat: publish docker image to DockerHub

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#556]
**What is the feature you would like to implement?**
Publish a Docker image to DockerHub and write a guide on how to run Hubble on AWS using Docker. 

**Why is this feature important?**
Make it easy for people who want to run Hubble as an image. 

**Will the protocol spec need to be updated??**
No

**Comment by alor** [comment]
I started writing a Dockerfile and a docker-compose.yml but if you plan to publish an official image I will wait yours.  My goal (if I find enough spare time) is to also write terraform scripts to facilitate the creation, installation and execution on DO droplets without much effort. just insert your DO token and launch `terraform apply`.  that's it.

**Comment by varunsrin** [comment]
terraform for DO would be awesome. 

tagging @sds -- does it make sense for alor to work on the dockerfile or is this already in progress?

**Comment by alor** [comment]
imho is cleaner if I just write the terraform script that pulls from your official docker image on docker hub.

**Comment by sds** [comment]
We have a [Dockerfile](https://github.com/farcasterxyz/hubble/blob/a3f6668b4f08e8d1e7960f8f4e9399d4eec20909/Dockerfile) already (unless I'm misunderstanding what we're talking about).

If the ask is to publish that image to Docker Hub, we need to decide which Docker Hub org to publish under. Would be ideal to have this be done automatically every time we tag a release for Hubble.

**Comment by sds** [comment]
We now publish a Docker image at https://hub.docker.com/r/farcasterxyz/hubble

You can pull the latest image using `docker pull farcasterxyz/hubble:latest`.
