### ISSUE TITLE
feat: authentication for rpc endpoints

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#558]
**What is the feature you would like to implement?**
Allow specifying authentication so that hub endpoints can't be accessed by unauthorized users. 

**Why is this feature important?**
Allows operators to limit access to public endpoints when necessary. 

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
TBD

**Comment by adityapk00** [comment]
Done
