### ISSUE TITLE
feat: reorg resiliency

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#561]
**What is the feature you would like to implement?**
Handle cases where a reorg can invalidate prior on chain actions in the id registry or name registry. 

**Why is this feature important?**
 Goerli can suffer from [long-ish reorgs](https://twitter.com/mysticryuujin/status/1624390681971105792?s=46&t=AWaCBIFPcz3YeagEC-Cx2w) which may become a problem as usage grows.

**Will the protocol spec need to be updated??**
No

**Comment by varunsrin** [comment]
Prior conversation about this issue 

> Right, we don't deal with the reorg issue right now. We have a few options:
> 1. Wait for the block to be finalized (instead of 6 blocks) ~15 mins. After a block is finalized, it can't be re-org'd
> 2. We can handle reorgs - Only handle reorg'd messages. That is, if a block with a event is re-orged, we will expect that message to be included in a subsequent block on the new chain, and when we recieve that message, we'll update the DB to reflect the new event. We can detect "duplicate" events, because they'll be the same fid/fname, but different blockhashes
> 3. We can ignore the reorg, and have a process for "invalidating" some events in the trie/DB, creating the expectation that these are rare, but possible.
> 4. We can use the "home hub" idea to ask a FID's home hub for its custody/fname events, and treat that as the authoritative source.
Option 2 is probably the most work.

**Comment by pfletcherhill** [comment]
Worth adding that handling reorgs will be challenging for hubs, since hubs don't have a concept of rewinding state. If a reorg happened, we could delete the events that came from the reorged blocks, but we wouldn't be able to retrieve any data that was overwritten by merging those events in the first place. Maybe there's a way of syncing events between hubs to fill these gaps?

**Comment by varunsrin** [comment]
One piece of data that would be useful before we make a decision here is the distribution and frequency of reorgs lengths since the merge.

**Comment by sds** [comment]
Now that we've migrated to OP Mainnet, this issue is best tracked in #1201.
