### ISSUE TITLE
feat: add dockerfile for Railway

### ISSUE THREAD

**Issue by vinliao** [farcasterxyz/hub-monorepo#707]
**What is the feature you would like to implement?**
Add a Railway part to the "deploying to the cloud" section in the Hubble docs, just a simple Dockerfile: https://gist.github.com/vinliao/8f41318e7ba5b55750e2b3ea198ca216.

**Why is this feature important?**
I've seen couple folks gain value from this, some of us prefer the simplicity of Railway. gRPC support is coming soon to Railway, so there's some things to smooth out. But as of now, anyone can just grab this and get Hubble up and running in five minutes (just run `railway up`).

**Will the protocol spec need to be updated??**
No.

**How should this feature be built? (optional)**
A design for the implementation of the feature

**Additional context**
I'm wondering if this is valuable enough to add to the docs.

**Comment by psatyajeet** [comment]
This would be pretty useful. We did something similar to setup a hub on AWS: https://github.com/bitwise-invest/farcaster-hub/blob/main/Dockerfile

**Comment by sds** [comment]
We now publish a Docker image for both AMD and ARM architectures at https://hub.docker.com/r/farcasterxyz/hubble.

Hope this helps!

**Comment by vinliao** [comment]
Thanks, just a note: Railway gRPC support isn't live yet, this ticket is blocked until Railway supports gRPC, that's why this ticket is open for months without updates.
