### ISSUE TITLE
feat: upgrade noble packages to v2

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#776]
**What is the feature you would like to implement?**
Upgrade the noble packages to v2 after they have baked for at least 4 weeks post-release. Use the new synchronous APIs which will require breaking changes (minor version bump) for hub-nodejs. 

**Why is this feature important?**
Noble v2 is smaller, claims to be more secure and has simpler interfaces so its a valuable improvement to our system.

**Will the protocol spec need to be updated??**
No

**Comment by paulmillr** [comment]
Things to keep in mind:

1. noble-curves are even more secure. They have more code, but, with tree-shaking, only features which are actually used are bundled.
2. ethers v6 uses secp256k1 v1 and plans to switch to noble-curves.
3. After the switch, using curves will allow using just one library and not two (curves, ed)
