### ISSUE TITLE
bug(hubble): killing gRPC streams that are stuck

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#823]

**Comment by adityapk00** [comment]
When a client opens a stream (via `subscribe()` and immediately sleeps, the server doesn't realize that the client is not draining the stream, and continously writes to the stream, which just keeps getting buffered, eventually running out of RAM and OOming. 

We can detect this situation on the server by monitoring the `memoryUsage.rss` and if it increases more than 1G during the loop, we can log them. 

The current plan is to log this error in production, and then decide what we want to do. We can decide to `destroy()` the stream to protect the hub.

**Comment by pfletcherhill** [comment]
Closed by https://github.com/farcasterxyz/hub-monorepo/pull/843
