### ISSUE TITLE
feat(hubble): hub runners should be able to check if their hub is in sync with the network

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#874]
**What is the feature you would like to implement?**
Hub runners need some way to check if their hubble instance is in sync with the rest of the network. 

**Why is this feature important?**
Hub runners need to able to set alerts to tell them if their hub is drifting away from the state of the network so that they can repair it. Otherwise, their applications will be showing out of data information. 

**Will the protocol spec need to be updated??**
No

**How should this feature be built?**

- Define some set of metrics for establishing if a hub is 'in sync' relative to its peers
- Periodically log those metrics
- (Optional) consider some way to visualize those metrics easily
- (Optional) run a global dashboard that shows the state of all hubs on the network

**Comment by psatyajeet** [comment]
This seems very valuable. Do you have any initial ideas?

**Comment by sanjayprabhu** [comment]
Right now, you can get this info by grepping for `SyncStatus` in the logs. We already have internal dashboards based on this. 

I've also added some initial metrics (message and event counts) to the `GetInfo` RPC call (https://github.com/farcasterxyz/hub-monorepo/pull/916). Plan is to also have it support querying the bootstrap nodes (or any other peer id provided) and return comparative counts and divergence prefix/timestamp.

And then have a user friendly version via a command on `yarn console`

**Comment by sanjayprabhu** [comment]
Fixed in https://github.com/farcasterxyz/hub-monorepo/pull/944. Running `yarn status` will print the hub's db stats and it's sync status w.r.t. it's bootstrap nodes.
