### ISSUE TITLE
bug(hubble): db size grows too fast during sync 

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#883]
**What is the bug?**
Sometimes when syncing a mainnet node from scratch the DB size grows to > 5gb, when it should only <1gb. This fixes itself on restart, but we've seen hubs crash because they took up all available disk space.

**How can it be reproduced? (optional)**
Start a fresh mainnet node and observe size of the db during sync.

**Additional context (optional)**
Suspect this is due to rocksdb compaction not kicking in.

**Comment by sanjayprabhu** [comment]
Still see this happening. Reopening

**Comment by varunsrin** [comment]
closing, since this should be resolved as of 1.3.3
