### ISSUE TITLE
bug(hubble): gossip is duplicating messages

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#885]
**What is the bug?**
@sagar-a16z reports:

> Lots of duplicate messages from gossip:

```
2|hubble  | {"level":40,"time":1681774144823,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774144000,"hash":"0x7481eb1f91045956b20416e159f90f0ca02805e│
4","fid":10512,"type":1},"source":"gossip","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}                                                                        │
2|hubble  | {"level":30,"time":1681774144933,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774144000,"hash":"0xccfbdb5709cc966760fbcfc5b0d0c1d72849359│
8","fid":2,"type":1},"source":"gossip","msg":"submitMessage success 296202014441472: fid 2 merged CAST_ADD 0xccfbdb5709cc966760fbcfc5b0d0c1d728493598"}                                                           │
2|hubble  | {"level":40,"time":1681774144937,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774144000,"hash":"0xccfbdb5709cc966760fbcfc5b0d0c1d72849359│
8","fid":2,"type":1},"source":"gossip","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}                                                                            │
2|hubble  | {"level":40,"time":1681774144940,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774144000,"hash":"0xccfbdb5709cc966760fbcfc5b0d0c1d72849359│
8","fid":2,"type":1},"source":"gossip","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}                                                                            │
2|hubble  | {"level":30,"time":1681774153154,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774153000,"hash":"0x4c7d386c4be95649db3d623c68ca49c7f22367e│
d","fid":4158,"type":1},"source":"gossip","msg":"submitMessage success 296202048118784: fid 4158 merged CAST_ADD 0x4c7d386c4be95649db3d623c68ca49c7f22367ed"}                                                     │
2|hubble  | {"level":40,"time":1681774153157,"pid":76678,"hostname":"ubuntu-farcaster-temp-node","component":"Hub","submittedMessage":{"timestamp":1681774153000,"hash":"0x4c7d386c4be95649db3d623c68ca49c7f22367e│
d","fid":4158,"type":1},"source":"gossip","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}  
```

> The same message is arriving from more than 1 place over gossip.
> It’s happening very quickly so (the duplicate delivery) so I think gossip doesn’t guard against it.
> But…there must be a way to signal to libp2p that the message was already received, that way it can update the mesh and cut off redundant pathways. @adityapk00 FYI

> It seems like with libp2p we can’t explicitly do that.
> There’s a message cache (seen cache) that stores recently (2min) seen messages.
> That prevents requesting for duplicates.
> But in this case what’s happening is that because the way gossip is configured by default (https://github.com/ChainSafe/js-libp2p-gossipsub/blob/v6.3.0/src/constants.ts) we will always get some duplicate broadcast to us I think especially while the network is small.
> I think the hub that creates the message is sending it to its peers (upto 12 connected) simultaneously + some peers not in its sub-mesh.
> All the nodes that get this message will then send it to their peers in the same fashion.
> I think that’s what’s causing this duplication.
> What’s good is that it seems like it’s only coming in 3 times. So we have 1 clear pathway (maybe direct from origin) and 2 redundant pathways.
>  But either way it might be good to go through that constants file and see what can be tuned for better perf

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by adityapk00** [comment]
I looked into this, and it looks like we already have the optimal config, which is 
```

const options = {
  emitSelf: false, // if you want to exclude self in messages
  gossipIncoming: false, // controls if incoming messages are automatically gossiped
  seenTTL: 1 * 60 * 1e3, // override the seen ttl to 1 minute
  historyLength: 5, // override the history length to something smaller
  historyGossip: 3, // override the history gossip
}
```

Instead, because of the way we do merges, we can do a very simple cache-and-check for dedups. Implemented here: https://github.com/farcasterxyz/hub-monorepo/pull/1081

**Comment by sanjayprabhu** [comment]
Should be addressed by the fix for https://github.com/farcasterxyz/hub-monorepo/issues/904
