### ISSUE TITLE
release: v1.3.0 on May 31

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#895]

**Comment by sanjayprabhu** [comment]
1.2 hubs will auto terminate on Jun 14. 

1.3 changes are tracked here: https://github.com/farcasterxyz/hub-monorepo/issues/895

Most notable user facing changes in this release are https://github.com/farcasterxyz/protocol/discussions/86 (not yet implemented) and https://github.com/farcasterxyz/hub-monorepo/pull/928

Planning to release to testnet around May 22 (depending on when multisignatures work gets in and the kind of dev coordination work required for it) and cut a release the following week.
