### ISSUE TITLE
bug: Sync issues v1.2

### ISSUE THREAD

**Issue by sanjayprabhu** [farcasterxyz/hub-monorepo#898]
**What is the bug?**
This is a tracking ticket for all the sync bugs we've noticed on v1.2. Splitting this into two sections, roughly categorized as "breaking" and "efficiency". Breaking bugs are anything that can cause hubs to never converge and always report as being out of sync or otherwise interfere with the normal operation of the hub. Efficiency bugs are the rest, where impact is mainly doing excessive syncs.

The net effect here is that the hubs is constantly syncing.

**Breaking**

1. Sync trie hashes don't match even after attempting to sync.
I'm seeing a lot of logs like this:
```
{"level":30,"time":1681935767288,"pid":56629,"hostname":"hubble","component":"SyncEngine","peerId":"12D3KooWRxgeFVLTAxeVgj4QHPzuT6HaV3Hj93LNZQeRi7gAwUVk","inSync":false,"isSyncing":false,"theirMessages":1089397,"ourMessages":1089391,"peerNetwork":1,"peerVersion":"2023.3.1","msg":"SyncStatus"}
{"level":30,"time":1681935767288,"pid":56629,"hostname":"hubble","component":"SyncEngine","peerId":"12D3KooWRxgeFVLTAxeVgj4QHPzuT6HaV3Hj93LNZQeRi7gAwUVk","msg":"Diffsync: Syncing with peer"}
{"level":30,"time":1681935767288,"pid":56629,"hostname":"hubble","component":"SyncEngine","msg":"Perform sync: Start"}
{"level":30,"time":1681935767289,"pid":56629,"hostname":"hubble","component":"SyncEngine","divergencePrefix":"007","prefix":"007247656","msg":"Divergence prefix"}
```

Where we're only off by a few messages but the divergence prefix is pretty high up and we never get back in sync. Still unclear what could be causing this (maybe missing custody events as reported by @pfletcherhill?)

2. Some hubs are getting stuck 100K+ messages behind
![image](https://user-images.githubusercontent.com/75855/233441623-57c2779f-df07-4149-b019-c2451424a243.png)
This could because of the missing eth events issue, or the hubs getting into some kind of sync loop or otherwise getting into a bad state.

**Efficiency** 

1. Truncated prefixes when comparing snapshots
e.g. logs
```
{"level":30,"time":1681935767289,"pid":56629,"hostname":"hubble","component":"SyncEngine","divergencePrefix":"007","prefix":"007247656","msg":"Divergence prefix"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","divergencePrefix":"007","prefix":"0072367","msg":"Divergence prefix"}
{"level":30,"time":1681935527221,"pid":56629,"hostname":"hubble","component":"SyncEngine","divergencePrefix":"00","prefix":"0072476320","msg":"Divergence prefix"}
```

The prefix length should always be 9 characters, but somehow we're getting 6-8 characters. This means we're comparing fewer levels of the trie than we should be causing inefficiency

2. Excluded hashes are compared to the second
I believe this is a regression introduced when we migrated to farcaster epochs.
https://github.com/farcasterxyz/hub-monorepo/blob/a027a3ed63f21949c0e74256df775b00635a752d/apps/hubble/src/network/sync/syncEngine.ts#L612-L614. When generating and comparing excluded hashes we should stop at the tens of seconds level so we don't try to sync messages that we'll get by gossip anyway. Depends on above issue with truncated prefixes being fixed first to realize benefits

4. Consistently attempting to sync with peers that are behind
We repeatedly attempt to sync with hubs that have far fewer messages. Either hubs that have just spun up, or hubs that have failed to catch up dues to issues above. The original intention behind not comparing message counts was that hubs could theoretically be ahead but have fewer message counts due to pruning. Some potential fixes:
 a) re-introduce message count comparison
 b) keep track of peers where we didn't successfully merge any messages and don't retry for a while

5. Divergence prefix is very high up even when messages are only off by <10
This may or may not be related to the first breaking issue, but want to track this separately in case it's something to do with how we generate excluded hashes (esp. now that we unload the trie from memory)

6. Messages counts are off by a lot between the ContactInfo and the SyncStatus RPC call
e.g. here, contactInfo reports `1070522` messages, but the RPC call reports `1085081`, a difference of 15K. This could be caused by  a delayed gossip message. But this combined with the partial prefix and the excluded hashes mismatch, I'm worried this is more indicative of some kind of merkle trie corruption.
```
{"level":30,"time":1681826805497,"pid":3855,"hostname":"hubble","component":"SyncEngine","peerId":"12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo","peerContact":{"gossipAddress":{"address":"52.20.72.19","family":4,"port":2282,"dnsName":""},"rpcAddress":{"address":"52.20.72.19","family":4,"port":2283,"dnsName":"hoyt.farcaster.xyz"},"excludedHashes":["af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9","af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9","6914e4174e48d96213302f4a1918654e703ab46a","6623b0716e708a9cdf95224e4e896b25539d1089","46afd2a82c45f3de3eeb01e31fef43b58d6e6c22","ea660d51b94ae971fcfa31a48fc0608fc93149cf","395599f4f7790384bce28664981dbae61039995c","1e5f4425fde71a034f1a79829cb30dff028c4483"],"count":1070522,"hubVersion":"2023.3.1","network":1},"msg":"Diffsync: Starting diff sync with peer"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","excludedHashesMatch":false,"msg":"shouldSync: excluded hashes"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","peerId":"12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo","inSync":false,"isSyncing":false,"theirMessages":1085081,"ourMessages":1085182,"peerNetwork":1,"peerVersion":"2023.3.1","msg":"SyncStatus"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","peerId":"12D3KooWRnSZUxjVJjbSHhVKpXtvibMarSfLSKDBeMpfVaNm1Joo","msg":"Diffsync: Syncing with peer"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","msg":"Perform sync: Start"}
{"level":30,"time":1681826805775,"pid":3855,"hostname":"hubble","component":"SyncEngine","divergencePrefix":"007","prefix":"0072367","msg":"Divergence prefix"}
```

**How can it be reproduced? (optional)**
Include steps, code samples, replits, screenshots and anything else that would be helpful to reproduce the problem. 

**Additional context (optional)**

**Comment by varunsrin** [comment]
closing in favor of https://github.com/farcasterxyz/hub-monorepo/issues/1045 and https://github.com/farcasterxyz/hub-monorepo/issues/873
