### ISSUE TITLE
feat: paginate subscribe fromId

### ISSUE THREAD

**Issue by zachterrell57** [farcasterxyz/hub-monorepo#918]
**What is the feature you would like to implement?**
I think it might be valuable to have a pagination option when subscribing `fromId`

**Why is this feature important?**
I'm not sure if this is the best way to get the behavior I'm looking for, so here's an example:
Let's say I want a rolling list of all events on a hub. I also want to be able to scroll and see all the events that have ever happened on the hub. Currently the way to do this would be to `subscribe` and set the `fromId` to 0. However, this would result in a massive response. It might make sense to instead paginate the response that comes from loading all event. 

**Will the protocol spec need to be updated??**
No

**Additional context**
Once again, this could be the wrong way to think about this. Feel free to offer another suggestion!

**Comment by varunsrin** [comment]
Hubs right now only have ~ 3 days of event data, after which they get pruned.  We could still add a pagination if this three day response is too large to handle, but is that what you are looking for?

**Comment by zachterrell57** [comment]
@varunsrin Yeah, I think it would still be worthwhile to paginate that response

**Comment by adityapk00** [comment]
This is now available in the HTTP API
