### ISSUE TITLE
bug: Unreliable sync times

### ISSUE THREAD

**Issue by alexpaden** [farcasterxyz/hub-monorepo#924]
**What is the bug?**
I have faced many issues with moderate to prolonged sync times from my hub to the Warpcast app.

While testing the "make-cast" tutorial today, I saw instant results for my newly created casts. Then, suddenly, I stopped seeing results for multiple minutes (1 within a minute, another within 5 minutes, and numerous now at 10minutes+).

While testing the "write-data" tutorial Yesterday from two accounts, it took up to 3 hours for profile picture changes to propagate, while casts that occurred after the PFP messages were published had quicker sync times.

**How can it be reproduced? (optional)**
I am not able to reliably reproduce or identify what is causing this.

**Additional context (optional)**
All messages are broadcast, and the results are OK. So far, I have not permanently lost any messages sent but have had up to multi-hour wait times.

**Comment by alexpaden** [comment]
Just an update my casts have now all come through after ~ 20-30 minutes each

**Comment by alexpaden** [comment]
I'm going to close this as the cast error I mentioned earlier is a result of the warpcast app not updating on desktop vs. mobile. However, the PFP changes from yesterday had still taken hours, and normal casts seem prioritized over it. Will query my hashes against your hub in the future

**Comment by varunsrin** [comment]
we've added more instrumentation around this, and aren't seen propagation delays across nodes. @alexpaden, any chance its related to your infra? have you seen more of this since you opened the issue?

**Comment by alexpaden** [comment]
I did not have many issues with this after the first month I posted it, infra was via DO and I don't think it was the problem since I have continued using it since (switching to neynar)
