### ISSUE TITLE
chore: create a system to track network propagation delay

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#933]
**What is the feature you would like to implement?**

A system that tracks how quickly messages propagate across hubs. The ideal, but impractical, system would have a god's eye view that observes new casts entering any hub and then measures how long it takes for that cast to show up on every other hub. 

**Why is this feature important?**

Our goal is for the Hub network to be as real-time as possible. Being able to measure this in an objective way will make it easier to improve over time. 

**Will the protocol spec need to be updated??**
No

**Comment by akshaan** [comment]
Here's the approach I'm thinking of taking for this, would love to get some feedback @sanjayprabhu @sagar-a16z :

New proto schemas:
```
syntax = "proto3";

enum NetworkLatencyMessageType {
  NETWORK_LATENCY_MESSAGE_NONE = 0;
  NETWORK_LATENCY_MESSAGE_PING = 1; // Ping sent from hub measuring network latency
  NETWORK_LATENCY_MESSAGE_ACK = 2; // Acknowledgement sent from hub receiving a ping message
}

message NetworkLatencyMessage {
    NetworkLatencyMessageType messageType = 1;
    oneof body {
        PingMessageBody ping_message = 2;
        AckMessageBody ack_message = 3;
    }
}

message PingMessageBody {
    string sender_peer_id = 1;
    uint32 ping_timestamp = 2;
}

message AckMessageBody {
    string sender_peer_id = 1;
    uint32 ping_timestamp = 2;
    uint32 ack_timestamp = 3;
}
```

Procedure: 
- When enabled (via CLI flag), a hub will send a `PingMessageBody` message with its peerId and the current timestamp to the gossip network on startup. The hub will also hold the current timestamp in memory.
- Hubs that receive the ping message will respond with an `AckMessageBody` with the sender's peerId and the current timestamp on the gossip network.
- When the sending hub receives an ACK message, it checks that the message peerId matches it's peerId and the message `ping_timestamp` field matches the value in memory. 
- When the sending hub's in-memory state has more than N records, it writes a log line with `ack_timestamp` and `ping_timestamp` for each of the records. This will be consumed by Datadog, where we can plot the mean and quantiles of network latency (i.e. `ack_timestamp - ping_timestamp`)
- After logging, the sending hub repeats the process by sending a new ping message to the network.

Questions:
- Do we need to send the ACK messages on the gossip network, or is there a direct p2p mechanism we can use to send ACKs from the receiving hub to the sending hub?
