### ISSUE TITLE
Keep getting a `node rocksdb` error and then exit

### ISSUE THREAD

**Issue by sljeff** [farcasterxyz/hub-monorepo#946]
**What is the bug?**

Keep getting this error and then exit:
```
3|hubble  | yarn run v1.22.19
3|hubble  | $ tsx src/cli.ts start -e https://goerli.infura.io/v3/XXXXXXXXXXXXXXXXXXXXXXX -b /dns/hoyt.farcaster.xyz/tcp/2282 -n 1
3|hubble  | {"level":30,"time":1683554534891,"pid":337583,"hostname":"ip-172-31-21-208","component":"utils/p2p","ip":"XX.XXX.XXX.XXX","msg":"Fetched public IP"}
3|hubble  | node: ../deps/rocksdb/rocksdb/db/write_batch.cc:1520: rocksdb::Status rocksdb::MemTableInserter::PutCFImpl(uint32_t, const rocksdb::Slice&, const rocksdb::Slice&, rocksdb::ValueType): Assertion `seq_per_batch_' failed.
3|hubble  | Done in 4.12s.
PM2       | App [hubble:3] exited with code [0] via signal [SIGINT]
PM2       | App [hubble:3] starting in -fork mode-
PM2       | App [hubble:3] online
```

**How can it be reproduced? (optional)**
It happened by itself without me changing

**Additional context (optional)**

**Comment by manan19** [comment]
I've tried `yarn dbreset` and the restarting but seeing the same issue

**Comment by varunsrin** [comment]
That's a database corruption issue we're trying to track down.  The best way to resolve the issue once it is to delete the `.rocks` folder and start hubble again, which will cause a full sync to happen. 

@sanjayprabhu believes its made worse by pm2's default startup behavior and encourages running with a restart delay like: `pm2 start "yarn start -e <node url> -b /dns/testnet1.farcaster.xyz/tcp/2282 -n 2" --name hubble --exp-backoff-restart-delay=100`

If you're using the restart delay and still seeing this issue, please let us know.

**Comment by Purp7ePi3** [comment]
I downloade database 3 times, but always same problem, i have to delay pm2 start?
Or it could be other issues?
