### ISSUE TITLE
feat(hubble): sync status with Ethereum should be easily determined by hub runners

### ISSUE THREAD

**Issue by deodad** [farcasterxyz/hub-monorepo#977]
**What is the feature you would like to implement?**
Synchronization status with Ethereum should be included in `yarn status`.

**Why is this feature important?**
Synchronizing Ethereum state is necessary for hubs to operate as expected. Since the JSON-RPC API provider must be configured by hub runners, this is a likely place for issues to crop up (i.e. rate limits, expired tokens, service outages). Being able to quickly confirm sync state will make diagnosing issues faster.

**Will the protocol spec need to be updated??**
Call out the sections of the [protocol spec](https://github.com/farcasterxyz/protocol) that will need to be updated (e.g. Section 4.3 - Verifications, Section 3.1 - Identity Systems) 
No

**How should this feature be built? (optional)**
Extend SyncStatusResponse to include a field for ethereum state that includes lastBlockNumber and lastTransactionHash for each synchronized contract event.

**Additional context**

**Comment by varunsrin** [comment]
The new grafana dashboards that @adityapk00 built solve for this issue
