### ISSUE TITLE
Bug(hub-nodejs/examples): Chron feed example script result in HubError: NotFound if one the fids is not resolved

### ISSUE THREAD

**Issue by Meyanis95** [farcasterxyz/hub-monorepo#978]
**What is the bug?**

Chron feed example script `index.ts` result in `HubError: NotFound` if one of the fids is not resolved to a fname.
I found that some fids are not resolved to a fname (e.g. fid: 12993) and it result in a broken script even if the other fids can be resolved.

**How can it be reproduced?**

You can reproduce the bug by running the`index.ts` script located in `hub-nodejs/examples/chron-feed/index.ts`, with the following FIDS array as a parameter.
`const FIDS = [2, 3, 12993];`

It will result with the following error:
```
Fetching fnames failed
HubError: NotFound: 
    at fromServiceError (file:///Users/yanismeziane/Desktop/hub-monorepo/packages/hub-nodejs/examples/chron-feed/node_modules/@farcaster/hub-nodejs/dist/index.mjs:6480:10)
```

The result expected should be to return the messages feed, with only the non resolved fnames as `undefined`.

**Potential solution**

Here is the actual code:
```js
  // 1. Create a mapping of fids to fnames, which we'll need later to display messages
  const fidToFname = new Map<number, string>();

  const fnameResultPromises = FIDS.map((fid) => client.getUserData({ fid, userDataType: UserDataType.FNAME }));
  const fnameResults = Result.combine(await Promise.all(fnameResultPromises));

  if (fnameResults.isErr()) {
    console.error('Fetching fnames failed');
    console.error(fnameResults.error);
    return;
  }
```

The workaround I found is the following one:

```js
  // 1. Create a mapping of fids to fnames, which we'll need later to display messages
  const fidToFname = new Map<number, string>();

  const fnameResultPromises = FIDS.map((fid) => client.getUserData({ fid, userDataType: UserDataType.FNAME }));
  const fnameResultPromisesSettled = await Promise.allSettled(fnameResultPromises);
  const successfulResults = fnameResultPromisesSettled
    .filter((result) => result.status === 'fulfilled')
    .map((result) => (result as PromiseFulfilledResult<Result<any, any>>).value)
    .filter((result) => result.isOk());
  const fnameResults = Result.combine(successfulResults);

  if (fnameResults.isErr()) {
    console.error('Fetching fnames failed');
    console.error(fnameResults.error);
    return;
  }
```

I'm open to do a PR if you think that this is a good solution and if the bug need to be resolved.

**Comment by varunsrin** [comment]
@Meyanis95 thanks for the report. 

I'm open to a PR, I think the right fix is to attempt to fetch the fnames and if one of the promises returns an error, replace it with a string like `fid:xyz` which can be used instead of the fname.
